### ISSUE TITLE
Podnoszenie

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1003]
ZZZXXXYY zapiera sie nogami o grunt i probuje uniesc poludniowo-zachodnia pordzewiala krate.

podnies poludniowo-zachodnia krate

**Comment by Delwing** [comment]
Nie binduje czy nie dziala bind?

**Comment by mwarzec** [comment]
Nie binduje.
Tam masz dwie różne kraty
na SW i na SE
Tę na SE bindowało.

**Comment by Delwing** [comment]
Wiem, że są różne, to jest powód zmian w podnoszeniu krat wiele releasów temu.

![image](https://user-images.githubusercontent.com/3740628/123507541-448e8380-d66a-11eb-8244-edc17a473ef6.png)
Może miałeś follow mode ustawiony na 0 lub 1 (i nie prowadzący podnosił).
