### ISSUE TITLE
Rozkrzaczona ramka postępów

### ISSUE THREAD

**Issue by asikowe** [tjurczyk/arkadia#1016]
Coś po ostatnich zmianach zaczęła się rozkrzaczać po prawej stronie tam, gdzie pojawiają się wpisy:

![image](https://user-images.githubusercontent.com/66479882/122877071-1b9a8580-d32e-11eb-8d72-c0fbfa8e79c0.png)

**Comment by Delwing** [comment]
Już jest na to poprawka, będzie w nowej wersji.
