### ISSUE TITLE
Transport - czasy przejazdu, opisy

### ISSUE THREAD

**Issue by Delwing** [tjurczyk/arkadia#1028]
Do nowej funkcjonalności potrzebuję zebrać troche danych... z całego świata. Nawet jeżeli baza nie będzie w 100% kompletna od razu to mam nadzieję w trakcie uzupełniać nowymi wpisami.
Chodzi o to, żeby skrypty pokazywały gdzie jesteśmy w danym statku/dyliżansie/wozie czy innym środku transportu.

Skrypty powinny móc zmienić swój stan czyli wiedzieć że postać wsiadła na statek, wiedzieć gdzie dany statek się aktualnie znajduję (pomiędzy którymi przystankami, oczywiście zakładając, że słyszeliśmy w którą stronę jedziemy i tak dalej).
Skrypty powinny być w stanie określić za ile dopłyniemy..

I tutaj potrzebuję Waszej pomocy. Część opisów już mamy, ponieważ są powiązane po prostu z ustawieniem mapy dla statków.
Postaram się tutaj wypisać te środki transportu w międzyczasie, żeby można było odznaczyć te już dodane/opisane. 

Funkcjonalność pojawi się nawet przy niepełnej bazie, będzie można ją na bieżąco uzupełnić.

Poniżej w komentarzu przykład opisu.

Statki

- [x]  kreutz-nuln-kz-bw
- [x]  marguilles-quenelles
- [x]  bodrog_quenelles
- [x]  nuln-bogenhafen
- [x]  kv-bw
- [x]  novigrad-wyspaslubow
- [x]  novigrad-bodrog-baccala
- [x]  baccala-meka
- [x]  rozrog-mekan
- [x]  faroe-skellige-rozrog
- [x]  skellige-hindersfjall
- [x]  skellige-kaerhemdall
- [x]  novigrad-skellige
- [x]  novigrad-oxenfurt-bialymost
- [x]  oxenfurt-blaviken
- [x]  novigrad-blaviken-daevon
- [x]  piana-hagge-sine
- [x]  novigrad-bodrog-scala
- [x]  novigrad-stocznia-nadrzecze
- [x]  oxenfurt-grabowabuchta
- [x]  alimento-kreutz
- [x]  quen-salignac quen-laki
- [x]  wstega-blaviken
- [x]  parravon-bretonia

Wozy, dylizanse

- [x] Wóz Maribor - Grabowa Buchta

**Comment by Delwing** [comment]
## Statek Piana-Hagge-Dolina Kwiatow

Kapitan: Haming

Wejście
```Wchodzisz na rzeczny transportowy statek.```

Wyjście
```Schodzisz ze statku.```

Start
```Statek odbija od brzegu.```

Przystanki (super, jeżeli będzie z numerem lokacji)
2616 ```Stary zgorzknialy mezczyzna krzyczy: Doplynelismy do drugiego pomostu w Pianie! Mozna wysiadac!```
10018 ```Stary zgorzknialy mezczyzna krzyczy: Doplynelismy do przystani w Hagge! Mozna wysiadac!```
8087 ```Stary zgorzknialy mezczyzna krzyczy: Doplynelismy do przystani w Starych Bukach! Mozna wysiadac!```

Czasy
```
Piana->Hagge 49s
Hagge -> Dolina kwiatow 45 s
Dolina kwiatow -> Hagge 57 s 
Hagge -> Piana 65s
```

**Comment by asikowe** [comment]
**Wóz Maribor - Grabowa Buchta**

Wejście
`Oplacasz podroz u woznicy i wsiadasz do drewnianego stojacego wozu.`

Wyjście (nie ma dodatkowego info)

Start
`Woznica donosnym glosem oznajmia odjazd.`

Przystanki:
180 `Z zewnatrz dochodzi stlumiony glos woznicy: Postoj, przystan powozowa.`
3342 `Z zewnatrz dochodzi stlumiony glos woznicy: Postoj, na dziedzincu zajazdu.`
3457 `Z zewnatrz dochodzi stlumiony glos woznicy: Postoj, centralny plac wioski.`
3252 `Z zewnatrz dochodzi stlumiony glos woznicy: Postoj, placyk w Grabowej Buchcie.`

Czasy
```
Maribor -> Zajazd 1.03s
Zajazd -> Kocie Pole 1.02s
Kocie Pole -> Grabowa Buchta 0.44s
```
---
**Prom Grabowa Buchta - Oxenfurt**

Wejście:
`Wchodzisz na duzy solidny prom.`

Wyjście:
`Schodzisz z promu.`

Start:
`Prom odbija od brzegu.`

Przystanki:
3542 `Grabowa Buchta [Z brzegu widać tylko, że Duzy solidny prom przybija do brzegu.]`
2464 `Mlody smutny mezczyzna krzyczy: Doplynelismy do przystani promu w Oxenfurcie! Mozna wysiadac!`

Czasy:
`Grabowa Buchta -> Oxenfurt 26s`

---
Właśnie doczytałam, że niektóre dane już masz... Mam jeszcze statek Oxen-Blavi i Blavi-Wstęga, ale jak już są, to nie będę wrzucać.

**Comment by Delwing** [comment]
Same opisy mamy co ustawiają pozycje (przynajmniej większość) ale dla porządku lepiej by było je wrzucić to nie będę musiał tego odszukiwać.

**Comment by asikowe** [comment]
**Statek Oxenfurt - Blaviken**

Kapitan: Malacius

Wejście:
`Wchodzisz na stara szkute.`

Wyjście:
`Schodzisz ze szkuty.`

Start:
`Szkuta odbija od brzegu.`

End:
`Szkuta przybija do brzegu.`

Przystanki:
2574 `Oxenfurt` [nie wiem co w tę stronę krzyczy - do dodania]
4059 `Malacius krzyczy: Doplynelismy do przystani w Blaviken! Mozna wysiadac!`

Czasy:
`Oxenfurt -> Blaviken 57s'

---

Statek Blaviken - Wstęga

Kapitan: Jacob

Wejście:
`Wchodzisz na smukly drakkar.`

Wyjście:
`Schodzisz z drakkara.`

Start:
`Drakkar odbija od brzegu.`

End:
`Drakkar przybija do brzegu.`

Przystanki:
4060 `Blaviken`  [nie wiem co w tę stronę krzyczy - do dodania]
6428 `Jacob krzyczy: Doplynelismy do przystani na Blekitnej Wstedze! Mozna wysiadac!`

Czasy:
`Oxenfurt - Błękitna Wstęga 2.55s`

**Comment by Monolith18** [comment]
Statek Quenelles-Verden

Kapitan:
```Francois Je L'icue, Kapitan brygu 'Brigadier-Duc'```

Wejscie:
```Wchodzisz na smukly bryg.```

Wyjscie:
```Schodzisz z brygu.```

Start:
```Zaloga odcumowuje statek, ktory powoli zaczyna odplywac od brzegu.```

Finish:
```Bryg z wolna doplywa do brzegu. Gdy lad jest juz dostatecznie blisko, kilku marynarzy sprawnie zeskakuje na ziemie i cumuje statek. Na koniec z pokladu zsuniety zostaje drewniany trap, pozwalajac na swobodne zejscie na brzeg.```

Przystanek Quenelles:
```
(mapper): ID lokacji: 4651
(mapper): Rejon lokacji: Quenelles
(mapper): Koordynaty lokacji: 81, 32, 0
(mapper): Waga lokacji: 20
(mapper): Wyjscia z lokacji: 
{
  west = 4652
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: Statek Quenelles - Verden
```

Przystanek Verden:
```
(mapper): ID lokacji: 3251
(mapper): Rejon lokacji: Verden
(mapper): Koordynaty lokacji: 76, 41, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  north = 3250
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: Statek Obawa - Quenelles
```

Czas (z Mudlet timestamp):
Quenelles-->Verden = 02m59s
Verden-->Quenelles = 03m05s

**Comment by Delwing** [comment]
Patrząc jeszcze na wstępną implementację istotne dla pojazdów z wieloma przystankami będzie jeszcze dla przystanków w środku trasy określać, w którą stronę się porusza.

Np.

`^(?:Haming|Stary zgorzknialy mezczyzna) krzyczy: Nastepnym portem bedzie przystan w Starych Bukach!$`

**Comment by Monolith18** [comment]
Statek Blekitna Wstega--Blaviken

Kapitan:
```Jacob Visenberg, Kapitan Ringhorna```

Wejscie:
```Wchodzisz na smukly drakkar.```

Wyjscie:
```Schodzisz z drakkara.```

Start:
```Drakkar odbija od brzegu.```

Finish:
```Drakkar przybija do brzegu.```

Przystanek BW:
```
(mapper): ID lokacji: 6428
(mapper): Rejon lokacji: Averland
(mapper): Koordynaty lokacji: 128, 62, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  east = 6427,
  west = 6429
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: Statek Blekitna Wstega - Blaviken
```

Przystanek Blaviken:
```
(mapper): ID lokacji: 4060
(mapper): Rejon lokacji: Polnocna Redania
(mapper): Koordynaty lokacji: 19, 23, 0
(mapper): Waga lokacji: 1
(mapper): Wyjscia z lokacji: 
{
  northwest = 4061,
  south = 4059
}
(mapper): Wyjscia specjalne z lokacji: 
{}
(mapper): Nazwa lokacji: Statek Blaviken - Blekitna Wstega
```

Czas (z Mudlet timestamp):
Blekitna Wstega-->Blaviken 03m03s

**Comment by Monolith18** [comment]
Statek Baccala-Rozrog-Novigrad

Kapitan:
```Charonda cesarski przewoznik, mezczyzna.```


Start:
```Statek odbija od brzegu.```

Wejscie:
```Wchodzisz na dwumasztowy nilfgaardzki statek.```

```
zapytaj kapitana o port
Pytasz Charonde o port.
Charonda syczy do ciebie: Nastepnym portem bedzie przystan w twierdzy Rozrog.
```

```
Statek przybija do brzegu.
Charonda krzyczy: Doplynelismy do przystani w twierdzy Rozrog! Mozna wysiadac!
```

```
zapytaj kapitana o port
Pytasz Charonde o port.
Charonda syczy do ciebie: Nastepnym portem bedzie poludniowe nabrzeze w Novigradzie.
```

```
Statek przybija do brzegu.
Charonda krzyczy: Doplynelismy do poludniowego nabrzeza w Novigradzie! Mozna wysiadac!
```


Czasy:

1m16sek Bacca-Rozrog
1m47sek Rozrog-Novi

**Comment by Monolith18** [comment]
Statek Urbimo-Novi

Kapitan:
```Annibale Malacresta Lettore, Kapitan statku "Spirito dell'Oceano", Tileanczyk.```

Wejscie:
```Wchodzisz na wielki trojmasztowy galeon.```

Wyjscie:
```Schodzisz z galeonu.```

Start:
```
Wysoki kruczowlosy mezczyzna (Annibale NPC) wchodzi na poklad galeonu.
Zaloga szybko odcumowuje statek, ktory powoli, majestatycznie zaczyna oddalac sie od brzegu.
```

```
Annibale krzyczy: Doplynelismy do poludniowego nabrzeza w Novigradzie! Mozna wysiadac!
```

```
Annibale krzyczy: Doplynelismy do przystani w Urbimo! Mozna wysiadac!
```

Czas:
Urbimo-Novi 3m25s
Novi-Urbimo 3m19s

**Comment by Monolith18** [comment]
Dylizans Varieno-Miragliano-Campogrotta

Wejscie:
```Oplacasz podroz u woznicy i wsiadasz do szarego stojacego dylizansu.```

Postoj w Varieno:
```
Woznica dylizansu glosno wola: Fermata - Varieno!
Woznica dylizansu glosno wola: Partire per Campogrotta in qualche minuti!
```

Postoj w Miragliano:
```
Z zewnatrz slyszysz glos woznicy: Fermata - incrocio alla Miragliano!
Z zewnatrz slyszysz glos woznicy: Partire per Campogrotta in qualche minuti!
```

Postoj w Campogrotta:
```
Z zewnatrz slyszysz glos woznicy: Fermata - Campogrotta!
Z zewnatrz slyszysz glos woznicy: Partire per Varieno in qualche minuti!
```

Start:
```Drzwiczki sie zamykaja, drzenie przebiega przez caly pojazd, ktory powoli rusza.```

Stop:
```Powoli pojazd zaczyna tracic predkosc, by po chwili zatrzymac sie.```


Czasy:
Varieno-Miragliano 54s
Miragliano-Campogrotta 40s

**Comment by asikowe** [comment]
**Novigrad - Skellige**

Kapitanka: 
`Hallgerda, kapitan knary 'Undvik', kobieta.`

Wejście
`Wchodzisz na szeroka knare.`

Wyjście
`Schodzisz z knary.`

Start
`Knara odbija od brzegu.`

Stop
`Knara przybija do brzegu.`

10311 `Hallgerda krzyczy: Doplynelismy do polnocnego nabrzeza na wyspie Ard Skellig! Mozna wysiadac!`
1907 `Hallgerda krzyczy: Doplynelismy do poludniowego nabrzeza w Novigradzie! Mozna wysiadac!`

Czasy:
`Novi -> Skell 1.36s`
