### ISSUE TITLE
Blokery / podążanie na mapie / mapa

### ISSUE THREAD

**Issue by jorhni** [tjurczyk/arkadia#104]
1. Brakujące blokery:
> Niski lysy sierzant marudzi do ciebie: Nikt z bronia nie wejdzie na teren Uniwersytetu. Prosze zostawic ja na stojaku.

> Odwazny przysadzisty oficer marudzi do ciebie: Nikt z bronia nie wejdzie na teren palacu. Prosze zostawic ja na stojaku.

2. Nie ma podążania w drużynie po mapie w chwili, kiedy nosimy klatkę do łowienia zwierząt:
> Wraz z xxx, yyy i zzz pomagacie bbb przeniesc duza zelazna klatke na wschod.

3. Zauważyłem, że od pewnej wersji mapy zniknął z niej obszar pod Karak Kadrin z Czarnymi Orkami i Trollami, nie wiem, czy to działanie zamierzone, czy gdzieś się przemknął jakiś błąd, więc zgłaszam.

**Comment by tjurczyk** [comment]
@jorhni 1 dodane, co do dwa: masz tekst jak wygląda jak są dwie osoby, które przeciągają?
3. ciężko powiedzieć, kilka rzeczy na mapie było robionych i mogło przypadkowo być usunięte.

**Comment by jorhni** [comment]
ad. 2 Przy dwóch osobach:
> Pomagasz Xxx przeniesc duza zelazna klatke na wschod.

ad. 3 Czy w jakis sposób można wspomóc w pracach nad mapą?

**Comment by tjurczyk** [comment]
@jorhni 

Co do mapy, to problematycznym jest to, że jeśli weźmiesz najnowszą mapę i coś w niej dodasz, to nie będzie ona uwzględniała Twoich zmian, dlatego też dotychczas działało to tak, że byłem informowany o brakach/błędach w mapie. Masz na myśli pojedyncze poprawki czy większe zmiany?

**Comment by jorhni** [comment]
@tjurczyk 
Od pewnego czasu przestałem nanosić zmiany właśnie ze względu na to, iż nie da się ich zachować przy aktualizacji. Więc dla mnie to nie problem.
To, co bym chciał ewentualnie nanieść, to choćby te jaskinie, o jakich pisałem, ustawić wagi lokacji przy trakcie na północ od Quenelles (/idzdo tam wariowało), wrzucić opisy tego, co kowale kują w poszczególnych kuźniach (/lok_opis) i co tam się urodzi.
Nie potrzebuję na to dużo czasu, powiedzmy ze dwa dni i zwracam Ci plik do dalszych prac.
Do środy jestem jeszcze na L4, więc czasem dysponuję.

**Comment by Walkir** [comment]
brakujace blokery:

Chwytasz za line i bez wiekszego wysilku, razno zaczynasz wspinac sie na szczyt urwiska.

Podchodzisz do cedru rosnacego na skraju urwiska i chwytajac liny, ktora zostala przywiazana do jego pnia, 
zaczynasz schodzic na dol.

**Comment by filipbober** [comment]
Brakuje także blokera podczas zmiany lokacji, gdy się płynie:

Jestes zajety plynieciem. Jesli chcesz uczynic cos innego, musisz 'przestac'.

**Comment by Walkir** [comment]
Probujesz wejsc w zakryte pajeczynami przejscie, lecz duzy szarawy golem odpycha cie brutalnie.
