### ISSUE TITLE
Mapper: Problem na łodzi w Baccali (w łodziach ogólnie?)

### ISSUE THREAD

**Issue by kociak1984** [tjurczyk/arkadia#1054]
Przypadek użycia: wsiadam z kimś (za kimś) do łodzi, siadam na ławie albo nie, nie ma znaczenia. Osoba wiosłuje, płynie w jakąś stronę, mi jako pasażerowi mapper stoi w miejscu.
Sprawdzane na aktualnej wersji, na razie tylko w Baccali.

**Comment by Delwing** [comment]
Fragment loga poproszę.

**Comment by kociak1984** [comment]
`21:59:08.830 [2] Podazasz za Xxxxxxx na polnoc, wchodzac na plycizne.
21:59:08.847 Zewszad otacza cie morze, choc plytko tu i ledwie kilka krokow od skraju stalego ladu. Woda drzy jak rozlana rtec, jak rozchwiane wiatrem lany zboza.
21:59:08.847 Co pol dnia morze bierze gleboki oddech i wypluwa spienione masy wody w kierunku klifowego brzegu. Pod cienka, szafirowa tonia rysuje sie wyraznie 
21:59:08.847 kamieniste dno. Zima otulila okolice biela i szaroscia, scinajac ja mroznym tchnieniem. Panuje ladna, zimowa pogoda.
21:59:08.936 Zacumowana wysluzona rybacka lodz.
21:59:14.911 Xxxxxxx wsiada do zacumowanej wysluzonej rybackiej lodzi.
21:59:17.999 wejdz do lodzi
21:59:18.055 Wsiadasz do zacumowanej wysluzonej rybackiej lodzi.
21:59:18.073 Stara lodz rybacka cala pokryta jest bialym nalotem, bedacym efektem plywania w slonej wodzie. Cedrowe szpanty wyginaja sie beczkowato i w lagodnym
21:59:18.073 luku schodza ku debowej stepce. Burty sa niezbyt wysokie, dno masywne, a dziob lekko zadarty. Wiele wiekow bliskiego sasiedztwa z morzem pozwolilo na 
21:59:18.073 stworzenie lodzi idealnej na trudne warunki pogodowe i niespokojny akwen.
21:59:18.152 Xxxxxxx.

21:59:22.477 Xxxxxxx zajmuje miejsce przy wioslach.
21:59:24.875 Xxxxxxx usmiecha sie dziwnie.
21:59:26.750 usiadz
21:59:26.804 Gdzie chcesz usiasc? Przy wioslach, na prawej burcie, na lewej burcie czy na drewnianej lawce?

21:59:26.804 bind ]: usiadz na drewnianej lawce


21:59:27.422 usiadz na drewnianej lawce
21:59:27.472 Siadasz wygodnie na drewnianej lawce.

21:59:31.417 Xxxxxxx odcumowuje zacumowana wysluzona rybacka lodz.
21:59:34.816 Xxxxxxx zaczyna wioslowac.
21:59:39.798 Xxxxxxx kieruje lodz na polnoc.
21:59:39.808 Powierzchnia morza.
21:59:39.815 Mozesz skierowac lodz na polnocny-wschod, poludniowy-wschod, poludnie, wschod, polnocny-zachod, poludniowy-zachod, polnoc oraz zachod.
21:59:39.852 Siedzisz na drewnianej lawce.
21:59:39.858 Przy wioslach siedzi Xxxxxxx.
21:59:44.965 Ciezkie mgly rozkladaja sie na calej powierzchni morza.
21:59:45.309 Xxxxxxx mowi pytajaco do ciebie: Zgubilo Cie?
21:59:46.206 'Ale ale.
21:59:46.259 Mowisz: Ale ale.

21:59:52.285 hmm
21:59:52.374 Hmmmmm...

21:59:57.246 Xxxxxxx zaczyna wioslowac.
22:00:00.195 Xxxxxxx kieruje lodz na poludnie.
22:00:00.208 W przybrzeznej toni.
22:00:00.214 Mozesz skierowac lodz na polnocny-wschod, wschod, polnocny-zachod, polnoc, poludniowy-zachod oraz zachod.
22:00:00.243 Siedzisz na drewnianej lawce.
22:00:00.250 Przy wioslach siedzi Xxxxxxx.
22:00:02.413 'do xxxxxxx To juz jest nietrywialne.
22:00:02.477 Mowisz do Xxxxxxx: To juz jest nietrywialne.

22:00:10.235 Xxxxxxx mamrocze pod nosem.
22:00:13.995 Xxxxxxx cumuje wysluzona rybacka lodz do brzegu.
22:00:16.732 'do xxxxxxx To juz wymaga opisania calym zakleciem, i to sporym.
22:00:16.896 Mowisz do Xxxxxxx: To juz wymaga opisania calym zakleciem, i to sporym.

22:00:21.916 wstan
22:00:21.965 Wstajesz z drewnianej lawki.

22:00:24.120 Xxxxxxx wydaje z siebie dlugie hmmmmm...
22:00:25.425 Xxxxxxx wstaje od wiosel.
22:00:26.332 wyjdz z lodzi
22:00:26.393 Wyskakujesz z lodzi.
22:00:26.404 Zewszad otacza cie morze, choc plytko tu i ledwie kilka krokow od skraju stalego ladu. Woda drzy jak rozlana rtec, jak rozchwiane wiatrem lany zboza.
22:00:26.404 Co pol dnia morze bierze gleboki oddech i wypluwa spienione masy wody w kierunku klifowego brzegu. Pod cienka, szafirowa tonia rysuje sie wyraznie 
22:00:26.404 kamieniste dno. Zima otulila okolice biela i szaroscia, scinajac ja mroznym tchnieniem. Panuje ladna, zimowa pogoda.
22:00:26.494 Zacumowana wysluzona rybacka lodz.

22:00:27.318 Xxxxxxx wyskakuje z zacumowanej wysluzonej rybackiej lodzi.
`
