### ISSUE TITLE
bloker poruszania sie

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1075]
Aby kierowac lodzia, musisz usiasc przy wioslach.

trigger_func_mapper_blockers_blocker()

**Comment by Delwing** [comment]
Czemu to jest bloker właściwie? Nie powinno być jakieś wsiadanie na łódź i dopiero siadanie powinno odblokować?

**Comment by mwarzec** [comment]
W przybrzeznej toni.
Zacumowana podniszczona rybacka lodz.

Wsiadasz do zacumowanej podniszczonej rybackiej lodzi.
Na podkladzie lodzi.
Zajmujesz miejsce przy wioslach.

se
Zaczynasz wioslowac.

Kierujesz lodz na poludniowy-wschod.
W przybrzeznej toni.
Mozesz skierowac lodz na polnoc, polnocny-zachod, zachod oraz wschod.
Siedzisz przy wioslach.
Jestes troche zmeczony.
Jestes wypoczety.
w  (przenosi na W mapę)
Zaczynasz wioslowac.

Jestes troche zmeczony.
Kierujesz lodz na zachod.  (przenosi jedze raz mapę na W) skacze o 2 lokacje wtedy.
W przybrzeznej toni.
Mozesz skierowac lodz na polnocny-wschod, wschod, polnocny-zachod, polnoc, poludniowy-zachod oraz zachod.
Siedzisz przy wioslach.
Fale morskie rozbijaja sie o burty lodzi.

Cumujesz podniszczona rybacka lodz do brzegu.
Wstajesz od wiosel.
Wyskakujesz z lodzi.
