### ISSUE TITLE
plywanie po morzu

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1079]
Mimo wlozenia wszystkich sil w wioslowanie nie jestes w stanie pokonac niezwykle silnego pradu wody.
- blokowanie przesuwania się

Nie masz juz sil walczyc z zywiolem i dajesz sie poniesc pradowi na dol.
Jezeli jestem w trakcie płynięcia.. to powinno cofnąć ruch na mapie.
Zaczynasz plynac na poludnie.
Nie masz juz sil walczyc z zywiolem i dajesz sie poniesc pradowi na dol.
Zapas powietrza wystarczy ci jeszcze na dlugo.

s
Zaczynasz plynac na poludnie.
Kilka ryb o wyciagnietych pyszczkach zachlannie oskubuje unoszona przez wode lisciasta lodyzke.
Udaje ci sie sprawnie przeplynac.

**Comment by Delwing** [comment]
Zestaw pauserow i blockerow powinien to rozwiązać.

Można sprawdzić 
```/zainstaluj Delwing/issue1075```
