### ISSUE TITLE
plywanie i przestawanie

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1085]
Powoduje przesuwanie mapy w momencie gdy przestaje plynac.
Na Baccali sprawdzone.
Moze lepiej zrobic, ze jak się zaczyna plynać to zapamiętuje kierunek i dopiero w momencie kiedy się przeplyneło to przestawia kierunek.

W tym przykładzie na polnoc mnie przenosilo za kazdym razem jak przestawalem plynać w dół.

Powierzchnia morza.
Mozesz stad poplynac na poludniowy-wschod, polnocny-wschod, poludnie, wschod, polnoc, polnocny-zachod, poludniowy-zachod
i zachod.
d
Zaczynasz plynac na dol.

Utrzymujesz sie na powierzchni wody.
przestan

Rezygnujesz z przeplyniecia.
u
Nie widzisz zadnego wyjscia prowadzacego na gore.

d
Zaczynasz plynac na dol.

przestan

Rezygnujesz z przeplyniecia.
d
Zaczynasz plynac na dol.

przestan

Rezygnujesz z przeplyniecia.
Utrzymujesz sie na powierzchni wody.

**Comment by Delwing** [comment]
Tam po prostu brakuje lokacji na "dole", należy je dodać do mapy.
