### ISSUE TITLE
Baccala morze

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1099]
Po wejściu do łodzi i przy pierwszym 'płynięciu' nie przesuwana znacznika na mapie.
Przesuwa dopiero przy kolejnym kroku.
![image](https://user-images.githubusercontent.com/62749025/132106565-d3e88d01-be5d-4765-879d-a9c5f8300d8e.png)

Pomylił się przy pierwszym plynięciu na SE. Zacumowalem łodź wg mapera na wodzie, choć jestem jedną lokację na SE względem tego co pokazuje.

Powierzchnia morza.
Mozesz stad poplynac na poludniowy-wschod, polnocny-wschod, wschod, poludnie, poludniowy-zachod, polnoc, polnocny-zachod
i zachod.
Na wodzie unosi sie wytrzymala rybacka lodz.
Jestes zmeczony.
Utrzymujesz sie na powierzchni wody.
uu
wejdz do lodzi;usiadz przy wioslach;/mn

 Kasuje znacznik na aktualnej lokacji.
Wdrapujesz sie do wytrzymalej rybackiej lodzi.
Na podkladzie lodzi.
Zajmujesz miejsce przy wioslach.

se
Jestes troche zmeczony.
Zaczynasz wioslowac.

Jestes zmeczony.
Kierujesz lodz na poludniowy-wschod.
Powierzchnia morza.
Mozesz skierowac lodz na polnocny-wschod, poludniowy-wschod, wschod, poludnie, poludniowy-zachod, polnoc, polnocny
-zachod oraz zachod.
Siedzisz przy wioslach.
Jestes troche zmeczony.
Krople wody powoli z ciebie skapuja.
e
Zaczynasz wioslowac.

Zmeczone szalenstwem morze powoli cichnie i uspokaja sie.
Kierujesz lodz na wschod.
W przybrzeznej toni.
Mozesz skierowac lodz na poludniowy-wschod, polnocny-wschod, poludnie, poludniowy-zachod, polnocny-zachod, polnoc oraz
zachod.
Siedzisz przy wioslach.
Jestes troche zmeczony.
Jestes troche zmeczony.
Krople wody powoli z ciebie skapuja.
zacumuj lodz
Cumujesz wytrzymala rybacka lodz do brzegu.
dd
wstan;wyjdz z lodzi;d;/mn 0

 Oznaczam aktualna lokacja numerem: 0
Wstajesz od wiosel.
Wyskakujesz z lodzi.
W przybrzeznej toni.
Zacumowana wytrzymala rybacka lodz.
Nie widzisz zadnego wyjscia prowadzacego na dol.

**Comment by Delwing** [comment]
Raczej naprawione.
