### ISSUE TITLE
Podwojne wyswietlenie pojemnika

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1108]
ob koszyk
Wypleciony z wikliny kosz sluzy przede wszystkim do noszenia codziennych zakupow. Mozna w nim rowniez przechowywac
pieczywo badz warzywa, zabierajac ze soba do wozu na jakas dluzsza podroz.
Jest zamkniety.

```otworz koszyk
Otwierasz duzy wiklinowy koszyk.

ob koszyk
Wypleciony z wikliny kosz sluzy przede wszystkim do noszenia codziennych zakupow. Mozna w nim rowniez przechowywac
pieczywo badz warzywa, zabierajac ze soba do wozu na jakas dluzsza podroz.
Jest otwarty.
Otwarty duzy wiklinowy koszyk zawiera wiele kruchych ciastek z orzechami.
------------------------------------- Pojemnik -----------------------------------
  ile   |        nazwa
----------------------------------------------------------------------------------
    wie | kruchych ciastek z orzechami
------------------------------------- Pojemnik -----------------------------------
  ile   |        nazwa
----------------------------------------------------------------------------------
    wie | kruchych ciastek z orzechami
```

**Comment by mwarzec** [comment]
`ob koszyk
Wypleciony z wikliny kosz sluzy przede wszystkim do noszenia codziennych zakupow. Mozna w nim rowniez przechowywac
pieczywo badz warzywa, zabierajac ze soba do wozu na jakas dluzsza podroz.
Jest zamkniety.

otworz koszyk
Otwierasz duzy wiklinowy koszyk.

ob koszyk
Wypleciony z wikliny kosz sluzy przede wszystkim do noszenia codziennych zakupow. Mozna w nim rowniez przechowywac
pieczywo badz warzywa, zabierajac ze soba do wozu na jakas dluzsza podroz.
Jest otwarty.
Otwarty duzy wiklinowy koszyk zawiera wiele kruchych ciastek z orzechami.
------------------------------------- Pojemnik -----------------------------------
  ile   |        nazwa
----------------------------------------------------------------------------------
    wie | kruchych ciastek z orzechami
------------------------------------- Pojemnik -----------------------------------
  ile   |        nazwa
----------------------------------------------------------------------------------
    wie | kruchych ciastek z orzechami`

**Comment by mwarzec** [comment]
Coś formatuje tekst więc wklejam grafikę.
![image](https://user-images.githubusercontent.com/62749025/132247545-14a11001-f041-416e-b6ef-ff93bd0c5d22.png)

**Comment by Delwing** [comment]
Do formatowania użyj 
3 x ` z obydwu stron tekstu

![image](https://user-images.githubusercontent.com/3740628/132404385-ba89e502-9d3b-491c-87eb-e2fd45a7afd8.png)
