### ISSUE TITLE
Asikowe - Raon

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1112]
No to te są.
Jedyne co to bym dodała bloka na drzwi, żeby nie przerzucało znacznika jak się próbuje je otworzyć bez kuli.

Probujesz otworzyc polyskujace wrota, ale nie udaje ci sie to.

Cofanie mapy.

**Comment by Delwing** [comment]
Czy można próbować je otworzyć komendą? (np. `otworz wrota`)

**Comment by asikowe** [comment]
Tak, wtedy też pojawia się ten sam tekst "Probujesz otworzyc..."
