### ISSUE TITLE
Zwiększenie wagi lokacji w goblinowie pod Nuln

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia#1126]
Obecnie kiedy puszcza się chodzik przez goblinowo (np. idąc do predefiniowanej lokacji), mapper automatycznie wytycza trasę przez środek. To oznacza, że idziemy prosto pod broń goblinów. Czy nie można by w mapie zwiększyć wagi lokacji goblinowa, pozostawiając domyślną ścieżkę np. po skrajnie południowej bandzie goblinowa, gdzie zazwyczaj mobów jest mniej?

**Comment by mwarzec** [comment]
Można, ale to do zrobienia w mapie jest a nie w samym skrypcie.
Masz mapę publiczną czy mapę 'rozwojową' ?

**Comment by chlebik** [comment]
Rozwojową

**Comment by Delwing** [comment]
Nie związane ze skryptami.
