### ISSUE TITLE
odblokowywanie mapy

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1147]
Zajmujesz miejsce przy wioslach.

/mm follow

Wynurzasz sie na powierzchnie.
Powierzchnia morza.
Mozesz stad poplynac na poludniowy-wschod, polnocny-wschod, poludnie, wschod, poludniowy-zachod, polnocny-zachod, polnoc i zachod.
Na wodzie unosi sie wytrzymala rybacka lodz.
Wdrapujesz sie do wytrzymalej rybackiej lodzi.
Na podkladzie lodzi.
Zajmujesz miejsce przy wioslach.

**Comment by Delwing** [comment]
Powinno być naprawione: #1137
