### ISSUE TITLE
Wyskoczenie za burtę statku/promu nie wyłacza paska

### ISSUE THREAD

**Issue by kociak1984** [tjurczyk/arkadia#1230]
Jak w opisie. Wyskoczenie za burtę po tym jak statek ruszył nie wyłacza paska, ten pozostaje i dalej odlicza swój czas. Obrazek długo po zejściu ze statku i skorzystaniu z jeszcze dwóch środków transportu.
![obraz](https://user-images.githubusercontent.com/10319543/144685906-587f3ff5-538d-4a96-8ae3-db3691e84b00.png)

**Comment by Delwing** [comment]
Czy dotyczy to najnowszej wersji skryptów? Problem był naprawiany (może nieskutecznie).

**Comment by kociak1984** [comment]
Mowa o 4.45. Przy poprzedniej wersji było to samo.

**Comment by Delwing** [comment]
Potrzebuję opis wyskakiwania przy którym się to stało.

**Comment by kociak1984** [comment]
Dla galeonu Novigrad-Urbimo:

> Jednym susem przesadzasz burte wielkiego trojmasztowego galeonu i wskakujesz do wody. Mimo duzego obciazenia po dluzszej chwili udaje ci sie doplynac z powrotem do brzegu.
