### ISSUE TITLE
kolorowanie wrogow

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1239]
Wyglada, ze tokenizacja postaci wymusza baze danych tylko z jednym wpisem danej postaci.
Przykład nie kolorowania wroga gdy jest podwójny wpis w bazie dla danego imienia.
Pewnie rozwiązaniem jest kompaktowanie bazy i elimianacja identycznych imion.
Nie wiem czy działa też na zasadzie identycznych opisów shortów. Jak znajdzie pierwszy to może nie sprawdzać dalej.

![image](https://user-images.githubusercontent.com/62749025/145287315-3f68720d-0e62-49f2-95f9-67f02d0c12c8.png)

![image](https://user-images.githubusercontent.com/62749025/145287352-383fea62-c8c8-49b3-8395-ddb400a84fdf.png)

**Comment by Delwing** [comment]
Sprawdzone na Kreganie w moim przypadku. Nie ma tego problemu.
