### ISSUE TITLE
dodaj_osobe - usprawnienie

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1259]
/dodaj_osobe Ktos#Jakas niemila elfka#Informacja od szpiega
(skrypty): Postac Ktos dodana do bazy. POD NUMEREM 5170
/przypomnij Ktos
/dodaj_do_gildii 5170 SC
(skrypty): Dodana gildia SC do postaci o imieniu Ktos i opisie: Jakas niemila elfka.

dodaj_osobe - niech zwraca NR rekordu w bazie pod jakim została dodana.
(skrypty): Postac Ktos dodana do bazy, OPIS Jakas niemila elfka POD NUMEREM 5170

**Comment by rawisz** [comment]
Nie trzeba dodawac po numerze, mozna po imieniu.
/dodaj_do_gildii Ktos SC

**Comment by Delwing** [comment]
```| /dodaj_osobe [imie]#[short]#[title] [gildia] - doda osobe do bazy.       |
| Komenda dziala jak ta powyzej oraz dodaje postac do gildii.              |```
Dodatkowo jest alias na dodanie postaci i od razu przypisanie do gildii, może przy okazji zrobię ten ID, chociaż na ten moment jest raczej zbędne.
