### ISSUE TITLE
Zlikwidowanie miejsca na ramki przy wyłączeniu graficznego wyglądu

### ISSUE THREAD

**Issue by asikowe** [tjurczyk/arkadia#1271]
Czołem,

Czy dałoby się przy wyłączeniu graficznego wyglądu muda zlikwidować też miejsce na ramki dookoła okienka kondycji? Przy małych ekranach (mam 13.3'') zajmuje to dużo istotnego miejsca. Przy walce drużynowej nie będzie widać, który członek drużyny co atakuje (przez tę niewielką ilość miejsca również zawijanie wierszy raczej nie wchodzi w grę).

![image](https://user-images.githubusercontent.com/66479882/150071563-fdf02244-2dbe-40ad-bcb4-0e1d6c2ad14a.png)

**Comment by asikowe** [comment]
I może dałoby się przy okazji przesunąć tę strzałkę po prawej bliżej JA/opisu moba?

**Comment by Delwing** [comment]
Done.
