### ISSUE TITLE
Spece goblinoidow - kolorek

### ISSUE THREAD

**Issue by asikowe** [tjurczyk/arkadia#1278]
Dalej nie działa:
![image](https://user-images.githubusercontent.com/66479882/150629432-49325364-e35c-4ca2-92de-a479f2b60340.png)

**Comment by Delwing** [comment]
A ustawiałaś kolor to cfg dla specy npcow?

**Comment by asikowe** [comment]
Tak.

**Comment by Delwing** [comment]
![image](https://user-images.githubusercontent.com/3740628/152264895-2a63ebce-c6dd-4abb-9d69-c03f54728d5c.png)
