### ISSUE TITLE
pekanie broni

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1338]
Jeżeli wystąpi walka bez broni, w ciągu do 5 sekund po pęknięciu broni - to drugi bind powinien odkladać broń złamaną i dobywać. Tak jak jest teraz to szybki cios i bind odkładania jest ponownie redefiniowany.

[  SPRZET  ] Ceremonialny dwureczny multon peka!

bind ]: odloz zlamana bron

[1/6] Ogromna zwinna endriaga ledwo muska cie zebami, trafiajac cie w nogi.
[bron] [1/6] Ledwo muskasz ogromna zwinna endriage lewa stopa, trafiajac ja w tulow.

****************************************
            Bijesz bez broni            
****************************************

bind ]: dobadz wszystkich broni

dobadz wszystkich broni
Zlamany ceremonialny dwureczny multon jest zlamany i nie nadaje juz sie do walki.

**Comment by Delwing** [comment]
Duplikat #1175
