### ISSUE TITLE
Dodanie wartości liczbowych do starożytnego kościanego berła + poprawki

### ISSUE THREAD

**Issue by asikowe** [tjurczyk/arkadia#1401]
OPISY, KTORE DOBRZE TAGUJE:

[1/6] Wykorzystujesz straszliwy ped starozytnego koscianego berla, ledwie zahaczajac zoltookiego
wyszczerzonego orka w korpus.

[1/6] Uderzasz starozytnym koscianym berlem, ledwie zahaczajac zoltookiego wyszczerzonego orka w
korpus.

[1/6] Bierzesz mocarny zamach starozytnym koscianym berlem, ledwie zahaczajac zoltookiego
wyszczerzonego orka w prawe ramie.

[4/6] Uderzasz starozytnym koscianym berlem, dotkliwie raniac zoltookiego wyszczerzonego orka w
korpus.

[4/6] Wyprowadzasz z furia uderzenie starozytnym koscianym berlem, dotkliwie raniac zoltookiego
wyszczerzonego orka w glowe.

[4/6] Wyprowadzasz z calej sily uderzenie starozytnym koscianym berlem, dotkliwie raniac zoltookiego
wyszczerzonego orka w nogi.

OPISY BEZ TAGOW:

Wyprowadzasz z furia uderzenie starozytnym koscianym berlem, nieznacznie tlukac zoltookiego
wyszczerzonego orka w korpus. -> [2/6]

Uderzasz starozytnym koscianym berlem, nieznacznie tlukac barczystego szkaradnego orka w korpus. -> [2/6]

Bierzesz mocarny zamach starozytnym koscianym berlem, nieznacznie tlukac zoltookiego wyszczerzonego
orka w korpus. -> [2/6]

Wykorzystujesz umiejetnie ped starozytnego koscianego berla, nieznacznie tlukac wymalowanego
dzikiego czarnego orka w nogi. -> [2/6]

Bierzesz mocarny zamach starozytnym koscianym berlem, bolesnie obijajac zoltookiego wyszczerzonego
orka w korpus. -> [3/6]

Uderzasz starozytnym koscianym berlem, bolesnie obijajac zoltookiego wyszczerzonego orka w korpus. -> [3/6]

Wykorzystujesz umiejetnie ped starozytnego koscianego berla, bolesnie obijajac muskularnego
agresywnego czarnego orka w nogi. -> [3/6]

Wyprowadzasz z impetem uderzenie starozytnym koscianym berlem, bolesnie obijajac zoltookiego
wyszczerzonego orka w korpus. -> [3/6]

Wyprowadzasz z furia uderzenie starozytnym koscianym berlem, bolesnie obijajac barczystego
szkaradnego orka w lewe ramie. -> [3/6]

Bierzesz straszliwy zamach starozytnym koscianym berlem, bolesnie obijajac wysokiego brudnego
czarnego orka w korpus. -> [3/6]

Wykorzystujesz umiejetnie ped starozytnego koscianego berla, bardzo ciezko lomoczac zwalistego
brutalnego czarnego orka w glowe. -> [5/6]

Wyprowadzasz z impetem uderzenie starozytnym koscianym berlem, bardzo ciezko lomoczac wysokiego
brudnego czarnego orka w korpus. [5/6]

Wyprowadzasz z furia uderzenie starozytnym koscianym berlem, bardzo ciezko lomoczac zoltookiego
wyszczerzonego orka w nogi. [5/6]

Podchodzisz do zoltookiego wyszczerzonego orka i z wymachu uderzasz starozytnym koscianym berlem,
zamieniajac korpus ofiary w krwawa miazge.
Zoltooki wyszczerzony ork umarl. -> [FIN]

MUDLET WYSWIETLA PODWOJNE WARTOSCI DLA:

[6/6] [6/6] Wykorzystujac dogodny moment wyprowadzasz celne uderzenie starozytnym koscianym berlem w
kudlatego wrednego hobgoblina, masakrujac go w glowe.

[5/6] [5/6] Wykorzystujac dogodny moment wyprowadzasz celne uderzenie starozytnym koscianym berlem w
zielonego okrutnego orka, bardzo ciezko raniac go w korpus.

**Comment by axesider** [comment]
Zobacz czy starozytne_kosciane_berlo masz nieaktywny

**Comment by asikowe** [comment]
W sensie gdzie?

**Comment by axesider** [comment]
W triggers

**Comment by asikowe** [comment]
Nie widzę tam w ogóle kościanego berła.
