### ISSUE TITLE
blocker - zmeczenie mentalne

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1405]
Aveth — Dziś o 20:08
przemknij e
Jestes zbyt wyczerpany mentalnie.

Mimo wszystko mapper się ruszył.
Da się to poprawić?

**Comment by rawisz** [comment]
Mud wysyla taka sama odpowiedz takze dla szukania, tropienia, szukania ziol.

**Comment by Delwing** [comment]
Można ew. dodać do `blocker_exprimental` i z włączonymi eksperymentalnymi blockerami zadziała.
