### ISSUE TITLE
Tabelki dla nowych kontenerów

### ISSUE THREAD

**Issue by N-a-t-t** [tjurczyk/arkadia#1410]
Czy można proszę dodać >regal< i >szkatule<do tabelek z itemami (na takiej zasadzie jak skrzynie, kufry itp)?

**Comment by rawisz** [comment]
Najlepiej by bylo jakbys wkleil jak jest dokladnie opis dla regalu&szkatuly (np. "Otwarta mosiezna skrzynia zawiera").
To co dodalem bedzie dzialac tylko jesli nie rozni sie od standardu. W razie czego zrobie poprawke.

**Comment by N-a-t-t** [comment]
Zdobiony sosnowy regal zawiera
Otwarta okragla zdobiona szkatula zawiera

Dzięki.
