### ISSUE TITLE
Polautomatyczna numeryczna

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia#1422]
Pisze z komy wiec sorry... 

Nie wiem czy tego juz nie ma, ale do skryptow mozna by dodac pluginy w zaleznosci od systemu i klawiatury z przygotowanymi klawiszami.

Np: wpisujesz
/klawiatura windows
I sciaga ci lub wlacza plugin zrobionych key do niej.

**Comment by Delwing** [comment]
Dostępne pod /konfiguracja
