### ISSUE TITLE
Podwójna wartość dla chybionego/wyparowanego tarczą ciosu zielonoskórych

### ISSUE THREAD

**Issue by asikowe** [tjurczyk/arkadia#1440]
Chybiony cios pojawia się teraz jako unik i 0/6:

[unk] [0/6] W slepiach postawnego dzikiego czarnego orka pojawia sie nienawistny blysk, gdy zdecydowanym uderzeniem czarnej zakrzywionej szabli przecina powietrze tuz przed twoja glowa.

[tar] [0/6] Wykorzystujac dogodny moment wyprowadzasz celne pchniecie asymetrycznym wulkanicznym
mlotem w wymalowanego spoconego czarnego orka, lecz ten oslania sie w pore okragla metalowa tarcza.

**Comment by tjurczyk** [comment]
Nie jestem w stanie zreplikowac 1, do drugiego trzeba zebrac opisy tego mlota i dodac je, jestes w stanie?

**Comment by asikowe** [comment]
Dobra, już wiem czemu nie mogłeś zreplikować pierwszego, można zignorować <walk_of_shame>.

Co do drugiego to już były zebrane https://github.com/tjurczyk/arkadia/issues/1328, chyba wystarczy tylko dodać ten nietrafiający, nie zorientowałam się, że jest przypisany do tej konkretnej broni.
