### ISSUE TITLE
zmiana bindu dla klawisza  ] 

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1448]
Zostało zmienione przejście.

Sindarion rusza w kierunku przegradzajacych droge glazow i znika za jednym z nich, wciskajac sie pod sciane wawozu.

bind ]: przejdz za glazy

po zmianie powinno być inaczej - byc przecisnij sie za glazy

**Comment by tjurczyk** [comment]
https://github.com/tjurczyk/arkadia/pull/1461
