### ISSUE TITLE
woreczki_buduj

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1473]
4 woreczki stare z ziolami, kupuje 4 nowe woreczki i daje ocenianie.
Efekt jest taki, ze pokazuje ile ziol jest w woreczkach starych - ale podaje stany nowych woreczkow

/woreczki_buduj
ocen 1. swoj woreczek

======= Oceniasz starannie zamkniety skorzany nieduzy woreczek. ========

Niewielki, skorzany woreczek, sluzacy do przechowywania ziol. Mozesz wlozyc do niego swoje roslinki, ktore ukryte w jego
przytulnym wnetrzu nie usychaja, chronione przed swiatlem i wysuszajacym wiatrem. Na woreczku widzisz godlo sklepu 
Osadnikow spod Puszczy Shekhal.
Jest zamkniety.

Oceniasz, ze zamkniety skorzany nieduzy woreczek wazy 240 gramow, zas jego objetosc wynosi 240 mililitrow.
Wydaje ci sie, ze jest wart okolo 50 miedziakow, czyli 4 sr, 2 mdz.
Ten element ekwipunku wyglada na calkiem nowy. [5/5]
ocen 2. swoj woreczek

======= Oceniasz starannie zamkniety skorzany nieduzy woreczek. ========

Niewielki, skorzany woreczek, sluzacy do przechowywania ziol. Mozesz wlozyc do niego swoje roslinki, ktore ukryte w jego
przytulnym wnetrzu nie usychaja, chronione przed swiatlem i wysuszajacym wiatrem. Na woreczku widzisz godlo sklepu 
Osadnikow spod Puszczy Shekhal.
Jest zamkniety.

Oceniasz, ze zamkniety skorzany nieduzy woreczek wazy 240 gramow, zas jego objetosc wynosi 240 mililitrow.
Wydaje ci sie, ze jest wart okolo 50 miedziakow, czyli 4 sr, 2 mdz.
Ten element ekwipunku wyglada na calkiem nowy. [5/5]
ocen 3. swoj woreczek

======= Oceniasz starannie zamkniety skorzany nieduzy woreczek. ========

Niewielki, skorzany woreczek, sluzacy do przechowywania ziol. Mozesz wlozyc do niego swoje roslinki, ktore ukryte w jego
przytulnym wnetrzu nie usychaja, chronione przed swiatlem i wysuszajacym wiatrem. Na woreczku widzisz godlo sklepu 
Osadnikow spod Puszczy Shekhal.
Jest zamkniety.

Oceniasz, ze zamkniety skorzany nieduzy woreczek wazy 240 gramow, zas jego objetosc wynosi 240 mililitrow.
Wydaje ci sie, ze jest wart okolo 50 miedziakow, czyli 4 sr, 2 mdz.
Ten element ekwipunku wyglada na calkiem nowy. [5/5]
ocen 4. swoj woreczek

======= Oceniasz starannie zamkniety skorzany nieduzy woreczek. ========

Niewielki, skorzany woreczek, sluzacy do przechowywania ziol. Mozesz wlozyc do niego swoje roslinki, ktore ukryte w jego
przytulnym wnetrzu nie usychaja, chronione przed swiatlem i wysuszajacym wiatrem. Na woreczku widzisz godlo sklepu 
Osadnikow spod Puszczy Shekhal.
Jest zamkniety.

Oceniasz, ze zamkniety skorzany nieduzy woreczek wazy 240 gramow, zas jego objetosc wynosi 240 mililitrow.
Wydaje ci sie, ze jest wart okolo 50 miedziakow, czyli 4 sr, 2 mdz.
Ten element ekwipunku wyglada na calkiem nowy. [5/5]
ocen 5. swoj woreczek

======= Oceniasz starannie zamkniety skorzany nieduzy woreczek. ========

Niewielki, skorzany woreczek, sluzacy do przechowywania ziol. Mozesz wlozyc do niego swoje roslinki, ktore ukryte w jego
przytulnym wnetrzu nie usychaja, chronione przed swiatlem i wysuszajacym wiatrem. Na woreczku widzisz godlo sklepu 
Osadnikow spod Puszczy Shekhal.
Jest zamkniety.

Oceniasz, ze zamkniety skorzany nieduzy woreczek wazy 1100 gramow, zas jego objetosc wynosi 1100 mililitrow.
Wydaje ci sie, ze jest wart okolo 13 miedziakow, czyli 1 sr, 1 mdz.
Ten element ekwipunku wyglada na kompletnie zuzyty. [1/5]
ocen 6. swoj woreczek

======= Oceniasz starannie zamkniety skorzany nieduzy woreczek. ========

Niewielki, skorzany woreczek, sluzacy do przechowywania ziol. Mozesz wlozyc do niego swoje roslinki, ktore ukryte w jego
przytulnym wnetrzu nie usychaja, chronione przed swiatlem i wysuszajacym wiatrem. Na woreczku widzisz godlo sklepu 
Osadnikow spod Puszczy Shekhal.
Jest zamkniety.

Oceniasz, ze zamkniety skorzany nieduzy woreczek wazy 1000 gramow, zas jego objetosc wynosi 1000 mililitrow.
Wydaje ci sie, ze jest wart okolo 28 miedziakow, czyli 2 sr, 4 mdz.
Ten element ekwipunku wyglada na w duzym stopniu zuzyty. [2/5]
ocen 7. swoj woreczek

======= Oceniasz starannie zamkniety skorzany nieduzy woreczek. ========

Niewielki, skorzany woreczek, sluzacy do przechowywania ziol. Mozesz wlozyc do niego swoje roslinki, ktore ukryte w jego
przytulnym wnetrzu nie usychaja, chronione przed swiatlem i wysuszajacym wiatrem. Na woreczku widzisz godlo sklepu 
Osadnikow spod Puszczy Shekhal.
Jest zamkniety.

Oceniasz, ze zamkniety skorzany nieduzy woreczek wazy 450 gramow, zas jego objetosc wynosi 450 mililitrow.
Wydaje ci sie, ze jest wart okolo 21 miedziakow, czyli 1 sr, 9 mdz.
Ten element ekwipunku wyglada na w duzym stopniu zuzyty. [2/5]
ocen 8. swoj woreczek

======= Oceniasz starannie zamkniety skorzany nieduzy woreczek. ========

Niewielki, skorzany woreczek, sluzacy do przechowywania ziol. Mozesz wlozyc do niego swoje roslinki, ktore ukryte w jego
przytulnym wnetrzu nie usychaja, chronione przed swiatlem i wysuszajacym wiatrem. Na woreczku widzisz godlo sklepu 
Osadnikow spod Puszczy Shekhal.
Jest zamkniety.

Oceniasz, ze zamkniety skorzany nieduzy woreczek wazy 1000 gramow, zas jego objetosc wynosi 1000 mililitrow.
Wydaje ci sie, ze jest wart okolo 21 miedziakow, czyli 1 sr, 9 mdz.
Ten element ekwipunku wyglada na w duzym stopniu zuzyty. [2/5]
ocen 9. swoj woreczek

Umm, co chcesz ocenic?
    Woreczki i ich stany:

  1. woreczek ........  [5/5]
  2. woreczek ........  [5/5]
  3. woreczek ........  [5/5]
  4. woreczek ........  [5/5]
  5. woreczek ........  [1/5]
  6. woreczek ........  [2/5]
  7. woreczek ........  [2/5]
  8. woreczek ........  [2/5]

/woreczki_pokaz

--------------------------- Ziola w twojej bazie -------------------------------
  ile |        nazwa             |              dzialanie                       
--------------------------------------------------------------------------------
                                                                                
                           1. woreczek (44 ziol) [5/5]

--------------------------------------------------------------------------------

                           2. woreczek (40 ziol) [5/5]

--------------------------------------------------------------------------------

                           3. woreczek (10 ziol) [5/5]

--------------------------------------------------------------------------------

                           4. woreczek (35 ziol) [5/5]

--------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/62749025/221256486-8b51fd87-e0a7-4c16-9bf6-76ce04471348.png)

**Comment by Delwing** [comment]
Zioła musisz przebudować.
