### ISSUE TITLE
Ziola - nie buduje poprawnie bazy ziolo-woreczek

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1482]
>>Do pasa masz przytroczone cztery zamkniete skorzane nieduze woreczki i duzy skorzany buklak.
Wydaje mi się, że powinien zaglądać do woreczków z opóźnieniem co jakieś np 100 ms. 

/ziola_pokaz

 ------+-------------------------+-----------------------------------------------
   ile |        nazwa            |              dzialanie                       
 ------+-------------------------+-----------------------------------------------
    1 | barwinek                | przyloz: +kon | zjedz: odtr
    2 | bez                     | zjedz: jadalny | przezuj: odtr?
    9 | bielun                  | powachaj: +zrc | zjedz: tr
    2 | bulawinka               | przezuj: +mana -kac | zjedz: tr
    1 | centuria                | zjedz: odtr
    3 | chaber                  | przezuj: odtr | powachaj: odtr | zjedz: +prg
    1 | czeremcha               | przezuj: +odp
   21 | deliona                 | zjedz: -zmc
    7 | dziurawiec              | rozgryz: +kon +zmc
    3 | glog                    | przezuj: +hp | zjedz: -zmc
    1 | janowiec                | zjedz: +prg
    4 | jaskier                 | rozkrusz: odtr | przezuj: tr | zjedz: tr
    1 | kasztanowiec            | przyloz: -zmc | zjedz: --
    5 | komosa                  | zjedz: -zmc | przezuj: +hp
    1 | krzyzownica             | przezuj: odtr | zjedz: jadalna
    2 | kulczyba                | przezuj: +sila | zjedz: tr
    3 | lak                     | przezuj: -zmc
    3 | lawenda                 | zjedz: +kon | przyloz: +odp
    7 | lukrecja                | przyloz: odtr | przezuj: +prg
    4 | lulecznica              | przezuj: -zmc
    3 | mieta                   | przezuj: +glod | rozetrzyj: +kon | powachaj: -zmc
    6 | mniszek                 | przezuj: +kon
    1 | nagietek                | przyloz: +kon +zmc
    2 | nawloc                  | rozgryz: odtr | zjedz: odtr | przyloz: odtr
    7 | ogorecznik              | przezuj: +odw
    2 | pieciornik              | rozgryz: +kon +kac | przezuj: odtr
    4 | plucnica                | sproszkuj: odtr
    6 | podbial                 | powachaj: -zmc | zjedz: jadalny
    7 | przelot                 | sproszkuj: odtr
    3 | rdest_ptasi             | przyloz: +kon | zjedz: --
    1 | rdest_wezownik          | przezuj: odtr
    2 | rosiczka                | polknij: -kac
    2 | serce_kapitana          | przezuj: +kon -int
    4 | siezygron               | rozgryz: odtr
    8 | skedar                  | przezuj: telepatia
    6 | szczwol                 | zjedz: tr | przyloz: -zmc
--------------------------------------------------------------------------------

Czujesz sie gorzej.
Czujesz sie bardziej zmeczony.
Jestes wypoczety.
Jestes ledwo zywy.
opusc bron
Opuszczasz srebrny kunsztowny miecz.

/z_przezuj serce_kapitana
otworz 3. swoj woreczek
wez 1 maly czerwony kwiat z 3. swojego woreczka
zamknij otwarte woreczki
przezuj 1 maly czerwony kwiat
Otwierasz skorzany nieduzy woreczek.

   WORECZEK OTWARTY - UPEWNIJ SIE ZE ZAMKNIESZ  
Wez co?
Zamykasz skorzany nieduzy woreczek.
Slucham?

Czujesz sie bezpiecznie.
/z_przyloz nagietek
otworz 3. swoj woreczek
wez 1 jasnopomaranczowy kwiat z 3. swojego woreczka
zamknij otwarte woreczki
przyloz 1 jasnopomaranczowy kwiat
Otwierasz skorzany nieduzy woreczek.

   WORECZEK OTWARTY - UPEWNIJ SIE ZE ZAMKNIESZ  
Wez co?
Zamykasz skorzany nieduzy woreczek.
Slucham?

/z_rozgryz dziurawiec
otworz 5. swoj woreczek
wez 1 czterokanciasta rozgaleziona lodyge z 5. swojego woreczka
zamknij otwarte woreczki
rozgryz 1 czterokanciasta rozgaleziona lodyge
Otworz co?
Wez skad?
Zamknij co?
Slucham?

/ziola_buduj
policz swoje woreczki
Doliczyles sie czterech sztuk.
zajrzyj do 1. swojego woreczka
zajrzyj do 2. swojego woreczka

Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz ciemne
poskrecane klacze, dwa wysokie blekitne kwiaty, jasnobrunatna popekana galazke, trzy rozgalezione wzniesione lodygi, trzy 
zlocistozolte kwiaty, trzy okraglawe aromatyczne liscie, szesc zoltych jasnych kwiatow, dwa ciemne gruzlowate grzyby, 
szarozielony gabczasty porost, dwie sztywne smukle lodygi, jasnozielona nieowlosiona lodyge, cztery zolte jaskrawe kwiaty, dwie 
duze granatowe jagody, czterokanciasta rozgaleziona lodyge, zielony galezisty ped i fioletowy lejkowaty kwiat.
zajrzyj do 3. swojego woreczka
Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz dwa zielone
galeziste pedy, dwa male czerwone kwiaty, jasnopomaranczowy kwiat, wysoki blekitny kwiat, dwa eliptyczne zaostrzone liscie, 
ulistniona aromatyczna galazke, dwie duze granatowe jagody, grube wygiete klacze, bialokwitnaca drobna roslinke, sztywny 
rozgaleziony korzen, dwa biale male kwiaty, dwa fioletowe zwarte kwiatostany, dwa zlocistozolte kwiaty, rozgaleziona wzniesiona 
lodyge, dwie jasnobrazowe ulistnione lodygi i ciemne poskrecane klacze.
zajrzyj do 4. swojego woreczka

Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz piec
czterokanciastych rozgalezionych lodyg, szesc ciemnych gruzlowatych grzybow, cztery macznistoowlosione szarawe rosliny, siedem 
zoltych jasnych kwiatow, trzy kremowe owlosione kwiaty, sztywna smukla lodyge, dwa zolte jaskrawe kwiaty, trzy jasnozielone 
nieowlosione lodygi, zoltawy powyginany korzen, bialokwitnaca drobna roslinke, szesc sztywnych rozgalezionych korzeni, dwa 
czarne aromatyczne ziarenka, bialy maly kwiat, fioletowy zwarty kwiatostan i zlocistozolty kwiat.
Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz wysoki
blekitny kwiat, osiem zoltych jasnych kwiatow, czterokanciasta rozgaleziona lodyge, dwa dziwne zoltoszare nasionka, szesc 
rozdetych aromatycznych lodyg, kosmatoowlosiony kwiatostan, wiotka kwitnaca galazke, cztery kremowe owlosione kwiaty, smukla 
jasnozielona lodyge, dziewiec duzych bialych kwiatow, trzy szarozielone gabczaste porosty, jasnobrunatna popekana galazke i 
piec eliptycznych zaostrzonych lisci.

(skrypty): Ok, zbudowalem baze ziol
/ziola_pokaz

 ------+-------------------------+-----------------------------------------------
   ile |        nazwa            |              dzialanie                       
 ------+-------------------------+-----------------------------------------------
    1 | barwinek                | przyloz: +kon | zjedz: odtr
    2 | bez                     | zjedz: jadalny | przezuj: odtr?
    9 | bielun                  | powachaj: +zrc | zjedz: tr
    2 | bulawinka               | przezuj: +mana -kac | zjedz: tr
    1 | centuria                | zjedz: odtr
    4 | chaber                  | przezuj: odtr | powachaj: odtr | zjedz: +prg
    1 | czeremcha               | przezuj: +odp
   21 | deliona                 | zjedz: -zmc
    7 | dziurawiec              | rozgryz: +kon +zmc
    3 | glog                    | przezuj: +hp | zjedz: -zmc
    1 | janowiec                | zjedz: +prg
    4 | jaskier                 | rozkrusz: odtr | przezuj: tr | zjedz: tr
    1 | kasztanowiec            | przyloz: -zmc | zjedz: --
    4 | komosa                  | zjedz: -zmc | przezuj: +hp
    1 | krzyzownica             | przezuj: odtr | zjedz: jadalna
    2 | kulczyba                | przezuj: +sila | zjedz: tr
    3 | lak                     | przezuj: -zmc
    3 | lawenda                 | zjedz: +kon | przyloz: +odp
    7 | lukrecja                | przyloz: odtr | przezuj: +prg
    4 | lulecznica              | przezuj: -zmc
    3 | mieta                   | przezuj: +glod | rozetrzyj: +kon | powachaj: -zmc
    6 | mniszek                 | przezuj: +kon
    1 | nagietek                | przyloz: +kon +zmc
    2 | nawloc                  | rozgryz: odtr | zjedz: odtr | przyloz: odtr
    7 | ogorecznik              | przezuj: +odw
    2 | pieciornik              | rozgryz: +kon +kac | przezuj: odtr
    4 | plucnica                | sproszkuj: odtr
    6 | podbial                 | powachaj: -zmc | zjedz: jadalny
    7 | przelot                 | sproszkuj: odtr
    3 | rdest_ptasi             | przyloz: +kon | zjedz: --
    1 | rdest_wezownik          | przezuj: odtr
    2 | rosiczka                | polknij: -kac
    2 | serce_kapitana          | przezuj: +kon -int
    4 | siezygron               | rozgryz: odtr
    8 | skedar                  | przezuj: telepatia
    6 | szczwol                 | zjedz: tr | przyloz: -zmc
--------------------------------------------------------------------------------

/z_przyloz rdest_ptasi
otworz 2. swoj woreczek
wez 1 zielony galezisty ped z 2. swojego woreczka
zamknij otwarte woreczki
przyloz 1 zielony galezisty ped
Otwierasz skorzany nieduzy woreczek.

   WORECZEK OTWARTY - UPEWNIJ SIE ZE ZAMKNIESZ  
Bierzesz zielony galezisty ped z otwartego skorzanego nieduzego woreczka.
Zamykasz skorzany nieduzy woreczek.
Przykladasz zielony galezisty ped.
Czujesz sie lepiej.

Gdzies w oddali rozlega sie wycie wilka.
/z_przyloz nagietek
otworz 3. swoj woreczek
wez 1 jasnopomaranczowy kwiat z 3. swojego woreczka
zamknij otwarte woreczki
przyloz 1 jasnopomaranczowy kwiat
Otwierasz skorzany nieduzy woreczek.

   WORECZEK OTWARTY - UPEWNIJ SIE ZE ZAMKNIESZ  
Wez co?
Zamykasz skorzany nieduzy woreczek.
Slucham?

/z_przezuj mniszek
otworz 2. swoj woreczek
wez 1 zlocistozolty kwiat z 2. swojego woreczka
zamknij otwarte woreczki
przezuj 1 zlocistozolty kwiat
Otwierasz skorzany nieduzy woreczek.

   WORECZEK OTWARTY - UPEWNIJ SIE ZE ZAMKNIESZ  
Bierzesz zlocistozolty kwiat z otwartego skorzanego nieduzego woreczka.
Zamykasz skorzany nieduzy woreczek.
Przezuwasz zlocistozolty kwiat.
Czujesz sie lepiej.

/z_rozetrzyj mieta
otworz 2. swoj woreczek
wez 1 okraglawy aromatyczny lisc z 2. swojego woreczka
zamknij otwarte woreczki
rozetrzyj 1 okraglawy aromatyczny lisc
Otwierasz skorzany nieduzy woreczek.

   WORECZEK OTWARTY - UPEWNIJ SIE ZE ZAMKNIESZ  
Wez co?
Zamykasz skorzany nieduzy woreczek.
Rozetrzyj co [jak] ?

**Comment by mwarzec** [comment]
Zaglądam do każdego osobno.

zajrzyj do 1. woreczka
Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz wiotka
kwitnaca galazke, smukla jasnozielona lodyge, 21 zoltych jasnych kwiatow, piec rozgalezionych wzniesionych lodyg i siedem 
czterokanciastych rozgalezionych lodyg.
 --------------------------- Ziola w tym woreczku -------------------------------
   ile |        nazwa            |              dzialanie                       
 ------+-------------------------+-----------------------------------------------
   21 | deliona                 | zjedz: -zmc
    1 | janowiec                | zjedz: +prg
    1 | centuria                | zjedz: odtr
    7 | dziurawiec              | rozgryz: +kon +zmc
    5 | jaskier                 | rozkrusz: odtr | przezuj: tr | zjedz: tr
--------------------------------------------------------------------------------

zajrzyj do 2. woreczka
Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz trzy
eliptyczne zaostrzone liscie, ulistniona aromatyczna galazke, grube wygiete klacze, dwie bialokwitnace drobne roslinki, siedem 
sztywnych rozgalezionych korzeni, dwa biale male kwiaty, trzy fioletowe zwarte kwiatostany, dwie jasnobrazowe ulistnione 
lodygi, cztery macznistoowlosione szarawe rosliny, siedem kremowych owlosionych kwiatow, zoltawy powyginany korzen, dwa czarne 
aromatyczne ziarenka, dwa dziwne zoltoszare nasionka, szesc rozdetych aromatycznych lodyg i kosmatoowlosiony kwiatostan.
 --------------------------- Ziola w tym woreczku -------------------------------
   ile |        nazwa            |              dzialanie                       
 ------+-------------------------+-----------------------------------------------
    4 | komosa                  | zjedz: -zmc | przezuj: +hp
    2 | nawloc                  | rozgryz: odtr | zjedz: odtr | przyloz: odtr
    1 | rdest_wezownik          | przezuj: odtr
    1 | czeremcha               | przezuj: +odp
    3 | lawenda                 | zjedz: +kon | przyloz: +odp
    2 | rosiczka                | polknij: -kac
    2 | bulawinka               | przezuj: +mana -kac | zjedz: tr
    7 | lukrecja                | przyloz: odtr | przezuj: +prg
    2 | kulczyba                | przezuj: +sila | zjedz: tr
    3 | ogorecznik              | przezuj: +odw
    1 | kasztanowiec            | przyloz: -zmc | zjedz: --
    6 | szczwol                 | zjedz: tr | przyloz: -zmc
    1 | krzyzownica             | przezuj: odtr | zjedz: jadalna
    2 | glog                    | przezuj: +hp | zjedz: -zmc
    7 | przelot                 | sproszkuj: odtr
--------------------------------------------------------------------------------

zajrzyj do 3. woreczka
Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz dwa
zlocistozolte kwiaty, trzy okraglawe aromatyczne liscie, osiem ciemnych gruzlowatych grzybow, cztery szarozielone gabczaste 
porosty, trzy sztywne smukle lodygi, cztery jasnozielone nieowlosione lodygi, szesc zoltych jaskrawych kwiatow, cztery duze 
granatowe jagody, dwa zielone galeziste pedy, fioletowy lejkowaty kwiat, dwa male czerwone kwiaty, jasnopomaranczowy kwiat i 
cztery eliptyczne zaostrzone liscie.
 --------------------------- Ziola w tym woreczku -------------------------------
   ile |        nazwa            |              dzialanie                       
 ------+-------------------------+-----------------------------------------------
    4 | lulecznica              | przezuj: -zmc
    4 | siezygron               | rozgryz: odtr
    8 | skedar                  | przezuj: telepatia
    1 | barwinek                | przyloz: +kon | zjedz: odtr
    1 | nagietek                | przyloz: +kon +zmc
    2 | rdest_ptasi             | przyloz: +kon | zjedz: --
    3 | lak                     | przezuj: -zmc
    4 | plucnica                | sproszkuj: odtr
    2 | serce_kapitana          | przezuj: +kon -int
    2 | mniszek                 | przezuj: +kon
    4 | ogorecznik              | przezuj: +odw
    3 | mieta                   | przezuj: +glod | rozetrzyj: +kon | powachaj: -zmc
    6 | podbial                 | powachaj: -zmc | zjedz: jadalny
--------------------------------------------------------------------------------

zajrzyj do 4. woreczka
Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz dziewiec
duzych bialych kwiatow, dwa ciemne poskrecane klacza, cztery wysokie blekitne kwiaty, dwie jasnobrunatne popekane galazki i 
trzy zlocistozolte kwiaty.
 --------------------------- Ziola w tym woreczku -------------------------------
   ile |        nazwa            |              dzialanie                       
 ------+-------------------------+-----------------------------------------------
    3 | mniszek                 | przezuj: +kon
    9 | bielun                  | powachaj: +zrc | zjedz: tr
    2 | pieciornik              | rozgryz: +kon +kac | przezuj: odtr
    4 | chaber                  | przezuj: odtr | powachaj: odtr | zjedz: +prg
    2 | bez                     | zjedz: jadalny | przezuj: odtr?
--------------------------------------------------------------------------------



/ziola_buduj
policz swoje woreczki
Doliczyles sie czterech sztuk.
zajrzyj do 1. swojego woreczka
zajrzyj do 2. swojego woreczka
zajrzyj do 3. swojego woreczka

Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz wiotka
kwitnaca galazke, smukla jasnozielona lodyge, 21 zoltych jasnych kwiatow, piec rozgalezionych wzniesionych lodyg i siedem 
czterokanciastych rozgalezionych lodyg.
zajrzyj do 4. swojego woreczka
Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz trzy
eliptyczne zaostrzone liscie, ulistniona aromatyczna galazke, grube wygiete klacze, dwie bialokwitnace drobne roslinki, siedem 
sztywnych rozgalezionych korzeni, dwa biale male kwiaty, trzy fioletowe zwarte kwiatostany, dwie jasnobrazowe ulistnione 
lodygi, cztery macznistoowlosione szarawe rosliny, siedem kremowych owlosionych kwiatow, zoltawy powyginany korzen, dwa czarne 
aromatyczne ziarenka, dwa dziwne zoltoszare nasionka, szesc rozdetych aromatycznych lodyg i kosmatoowlosiony kwiatostan.
Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz dwa
zlocistozolte kwiaty, trzy okraglawe aromatyczne liscie, osiem ciemnych gruzlowatych grzybow, cztery szarozielone gabczaste 
porosty, trzy sztywne smukle lodygi, cztery jasnozielone nieowlosione lodygi, szesc zoltych jaskrawych kwiatow, cztery duze 
granatowe jagody, dwa zielone galeziste pedy, fioletowy lejkowaty kwiat, dwa male czerwone kwiaty, jasnopomaranczowy kwiat i 
cztery eliptyczne zaostrzone liscie.

Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz dziewiec
duzych bialych kwiatow, dwa ciemne poskrecane klacza, cztery wysokie blekitne kwiaty, dwie jasnobrunatne popekane galazki i 
trzy zlocistozolte kwiaty.

/ziola_pokaz

 ------+-------------------------+-----------------------------------------------
   ile |        nazwa            |              dzialanie                       
 ------+-------------------------+-----------------------------------------------
/woreczki_pokaz

--------------------------- Ziola w twojej bazie -------------------------------
  ile |        nazwa             |              dzialanie                       
--------------------------------------------------------------------------------
                                                                                
                           1. woreczek (0 ziol) [5/5]

--------------------------------------------------------------------------------

                           2. woreczek (35 ziol) [5/5]

--------------------------------------------------------------------------------

                           3. woreczek (44 ziol) [5/5]

--------------------------------------------------------------------------------

                           4. woreczek (20 ziol) [5/5]

--------------------------------------------------------------------------------

**Comment by mwarzec** [comment]
A teraz tak..
policz swoje woreczki
Doliczyles sie czterech sztuk.
zajrzyj do 1. swojego woreczka

Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz siedem
czterokanciastych rozgalezionych lodyg, piec rozgalezionych wzniesionych lodyg, 21 zoltych jasnych kwiatow, smukla 
jasnozielona lodyge i wiotka kwitnaca galazke.
zajrzyj do 2. swojego woreczka

Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz
kosmatoowlosiony kwiatostan, szesc rozdetych aromatycznych lodyg, dwa dziwne zoltoszare nasionka, dwa czarne aromatyczne 
ziarenka, zoltawy powyginany korzen, siedem kremowych owlosionych kwiatow, cztery macznistoowlosione szarawe rosliny, dwie 
jasnobrazowe ulistnione lodygi, trzy fioletowe zwarte kwiatostany, dwa biale male kwiaty, siedem sztywnych rozgalezionych 
korzeni, dwie bialokwitnace drobne roslinki, grube wygiete klacze, ulistniona aromatyczna galazke i trzy eliptyczne 
zaostrzone liscie.
zajrzyj do 3. swojego woreczka

Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz cztery
eliptyczne zaostrzone liscie, jasnopomaranczowy kwiat, dwa male czerwone kwiaty, fioletowy lejkowaty kwiat, dwa zielone 
galeziste pedy, cztery duze granatowe jagody, szesc zoltych jaskrawych kwiatow, cztery jasnozielone nieowlosione lodygi, 
trzy sztywne smukle lodygi, cztery szarozielone gabczaste porosty, osiem ciemnych gruzlowatych grzybow, trzy okraglawe 
aromatyczne liscie i dwa zlocistozolte kwiaty.
zajrzyj do 4. swojego woreczka

Rozwiazujesz na chwile rzemyk, sprawdzajac zawartosc swojego skorzanego nieduzego woreczka. W srodku dostrzegasz trzy
zlocistozolte kwiaty, dwie jasnobrunatne popekane galazki, cztery wysokie blekitne kwiaty, dwa ciemne poskrecane klacza i 
dziewiec duzych bialych kwiatow.


/ziola_pokaz

 ------+-------------------------+-----------------------------------------------
   ile |        nazwa            |              dzialanie                       
 ------+-------------------------+-----------------------------------------------
    1 | barwinek                | przyloz: +kon | zjedz: odtr
    2 | bez                     | zjedz: jadalny | przezuj: odtr?
    9 | bielun                  | powachaj: +zrc | zjedz: tr
    2 | bulawinka               | przezuj: +mana -kac | zjedz: tr
    1 | centuria                | zjedz: odtr
    4 | chaber                  | przezuj: odtr | powachaj: odtr | zjedz: +prg
    1 | czeremcha               | przezuj: +odp
   21 | deliona                 | zjedz: -zmc
    7 | dziurawiec              | rozgryz: +kon +zmc
    2 | glog                    | przezuj: +hp | zjedz: -zmc
    1 | janowiec                | zjedz: +prg
    5 | jaskier                 | rozkrusz: odtr | przezuj: tr | zjedz: tr
    1 | kasztanowiec            | przyloz: -zmc | zjedz: --
    4 | komosa                  | zjedz: -zmc | przezuj: +hp
    1 | krzyzownica             | przezuj: odtr | zjedz: jadalna
    2 | kulczyba                | przezuj: +sila | zjedz: tr
    3 | lak                     | przezuj: -zmc
    3 | lawenda                 | zjedz: +kon | przyloz: +odp
    7 | lukrecja                | przyloz: odtr | przezuj: +prg
    4 | lulecznica              | przezuj: -zmc
    3 | mieta                   | przezuj: +glod | rozetrzyj: +kon | powachaj: -zmc
    5 | mniszek                 | przezuj: +kon
    1 | nagietek                | przyloz: +kon +zmc
    2 | nawloc                  | rozgryz: odtr | zjedz: odtr | przyloz: odtr
    7 | ogorecznik              | przezuj: +odw
    2 | pieciornik              | rozgryz: +kon +kac | przezuj: odtr
    4 | plucnica                | sproszkuj: odtr
    6 | podbial                 | powachaj: -zmc | zjedz: jadalny
    7 | przelot                 | sproszkuj: odtr
    2 | rdest_ptasi             | przyloz: +kon | zjedz: --
    1 | rdest_wezownik          | przezuj: odtr
    2 | rosiczka                | polknij: -kac
    2 | serce_kapitana          | przezuj: +kon -int
    4 | siezygron               | rozgryz: odtr
    8 | skedar                  | przezuj: telepatia
    6 | szczwol                 | zjedz: tr | przyloz: -zmc
--------------------------------------------------------------------------------

**Comment by tjurczyk** [comment]
Budowanie dziala teraz na coroutines wiec nie powinno byc juz tego problemu. Sprawdzilem twoje woreczki i wszystkie sie drukuja poprawnie wiec powinno juz wszystko dzialac. Gdyby nie dzialalo, zglos na discordzie i znowu zobaczymy
