### ISSUE TITLE
dobywanie jednoracz, dwurecznych broni

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#1525]
Zauwazasz, iz miecz jest przystosowany do chwytania oburacz, jednak ty bylbys w stanie dobyc go w dowolnej
rece.
Za jego pomoca mozna zadawac rany klute i ciete.
Twoje doswiadczenie i umiejetnosci podpowiadaja ci, ze jak na dwureczny miecz jest on genialnie wywazony i
zabojczo skuteczny.

Nie formatuje skroconego opisu

Zauwazasz, iz miecz jest przystosowany do chwytania oburacz___, jednak ty bylbys w stanie dobyc go w dowolnej
rece.___

**Comment by axesider** [comment]
Poprawione w #1527
