### ISSUE TITLE
[WOZY / BRYCZKI] - bindy przy wsiadaniu / zsiadaniu dla druzyny

### ISSUE THREAD

**Issue by felixd** [tjurczyk/arkadia#1528]
Dodanie bindów dla wozów i bryczek dla drużyny (tak jak bindy na statek)

Klawisz: `[`

## Bryczka

* Usiądz: `usiadz w bryczce`

```
XYZ siada w ##### ##### **bryczce**.
```

* Wstan: `wstan`

```
XYZ zsiada z ##### ##### **bryczki**.
```

## Woz - średni/duży

* Usiądź: `usiadz na wozie`

```
XYZ siada na ##### ##### **wozie**.
```

* Wstan: `wstan`
 
```
XYZ zsiada z ##### ##### wozu.
```

**Comment by tjurczyk** [comment]
https://github.com/tjurczyk/arkadia/pull/1557
