### ISSUE TITLE
Zakanczanie wrogom

### ISSUE THREAD

**Issue by najwyzej** [tjurczyk/arkadia#1612]
Prosze o dodanie komunikatu w odpowiednim miejscu: Probujesz zakonczyc wrogowi przed uplywem 10 minut. Nalozona na Ciebie zostanie dozywotnia hanba poczatkujacego mlokosa i bedziesz wysmiewany przez kolejne dziesiec lat na discordzie. Czy jestes pewien, ze chcesz to zrobic? Jesli tak, wpisz 'zakoncz'.

Uzasadnienie: Do gry dolaczala nowe osoby albo powracaja starzy gracze, ktorzy juz nie pamietaja albo nie znaja niepisanego kodeksu honorowego Arkadii i warto to dodac, zeby oszczedzic im zazenowania.

**Comment by Delwing** [comment]
To nie jest sprawa dla skryptów.
