### ISSUE TITLE
Dodanie przypominajki o płaszczu.

### ISSUE THREAD

**Issue by ftpd** [tjurczyk/arkadia#176]
Pomysł:
- po zakończeniu walki (w dowolny sposób, pewnie z GMCP da się to wyjąć) mógłby odpalać się timer, który po 30 sekundach (czas sprawdzony na arce) przypomina o płaszczu;
- przypomnienie mogłoby lecieć w pole alert albo po prostu się bindować - ewentualnie może osobne pole 'Plaszcz:' na pasek, w stanie on/off (jeśli pole, to pewnie z odliczaniem, jak wszystkie inne :P)
- oczywiście jeśli w międzyczasie rozpocznie się nowa walka, timer niech się zeruje.

**Comment by Delwing** [comment]
W pewnej formie zaimplementowane - wywołanie komendy wymagającej ochłonięcia wyświetla bind pod koniec czasu + na dole w pasku jest timer
