### ISSUE TITLE
Szablon do listow

### ISSUE THREAD

**Issue by animal793** [tjurczyk/arkadia#191]
Witam na forum wybrzmialo pytanie o listy.

I w sumie przydalby sie nam jakis szablon do listow w ksztalcie zwoju rozwinietego/poszarpanego kawala skory czy czegokolwiek.

Tak mi wpadlo na mysl ze wielu osobom by sie przydalo a listy schudniej od razu wygladaja i bardziej klimatycznie.

Pozdrawiam.

**Comment by Walkir** [comment]
Tutaj jest coś takiego:
http://arkadia.rpg.pl/forum/viewtopic.php?f=15&t=704

**Comment by ftpd** [comment]
I nagle pół arki pisze z jednego szablonu <3

**Comment by Delwing** [comment]
Jakiś czas temu została dodana komenda `/list`
