### ISSUE TITLE
Licznik czasu do otulenia sie plaszczem

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia#250]
Przydałby się licznik (być może opcjonalny, jeśli komuś zbędny) odliczający czas do otulenia się płaszczem. To zresztą ten sam czas co zakańczanie i zrywanie. Razem z licznikiem manewrów, ukrywania (już zaimplementowanymi) i licznikiem zażywania ziół (zgłoszonym) byłby komplet. Fajnie, gdyby dało się wyświetlać je wszystkie w panelu dolnym.

Wydaje mi się, że to jest równo trzydzieści sekund.

**Comment by tjurczyk** [comment]
Aby cos takiego zaimplementowac potrzebny jest sprawdzony czas. Nie wiem czy w pasku dolnym jest na to miejsce. Potrzebne byloby raczej dodanie kolejnego (piatego) wiersza.

**Comment by filipbober** [comment]
Sprawdziłem. Czas to 30 sekund.

Jeśli w planach są zioła to i tak będzie potrzebny licznik ziół. Jeden i drugi zaczyna odliczać od przerwania walki, z tym, że zioła 3s, a otulanie 30s. Jedna linijka mogłaby załatwić jedno i drugie. A może przy czasie ukrywania dodać na zielono/czerwono literkę z (zioła) i o (otulanie)?

**Comment by filipbober** [comment]
Pod ten sam czas co otulanie płaszczem (30 sekund) podchodzi jeszcze atak z zaskoczenia.

**Comment by Delwing** [comment]
W pewnej formie zaimplementowane - wywołanie komendy wymagającej ochłonięcia wyświetla bind pod koniec czasu.
