### ISSUE TITLE
odliczanie po zakończeniu walki

### ISSUE THREAD

**Issue by pprraavv** [tjurczyk/arkadia#335]
W Arkadii jest sporo czynności, których nie można wykonać od razu po skończonej walce. Trzeba trochę odczekać, a próba wykonania akcji wcześniej skutkuje komunikatem "...ochlon troche od walki."

Czy można zrobić licznik liczący do przodu, startujący w momencie zakończenia/wycofania/zaprzestania walki? Licznik liczyłby do powiedzmy 45s, potem wyświetlał stałą wartość >45.
Nawiązanie walki skutkowało by zerowaniem licznika (również w trakcie odliczania).
Większość znanych mi akcji ma karencję rzędu 30 sekund, stąd propozycja liczenia do 45. 

Zastanawiam się jak wykryć koniec udziału w walce. Czy wystarczyło by sprawdzanie Objects.Data w poszukiwaniu wrogów/atakujących na lokacji? Wówczas jeśli ich nie ma, to count+1, aż do 45. 

W GMCP trzeba by sprawdzać czy na lokacji są:
- enemy - BOOLEAN, czy obiekt jest wrogiem w walce postaci gracza
- avatar_target - BOOLEAN, czy postac gracza koncentruje sie w walce na tym obiekcie
- plus jakiś trigger wykrywający walkę bez wzroku (wtedy GMCP chyba nie ma, ale są opisy w stylu ktoś atakuje ciebie)

Całość trzeba by przetestować, bo nie wiem jak w GMCP widoczna jest sytuacja, gdy ukryta postać ma dokoła wrogów, którzy go nie widzą. Licznik wówczas powinien chyba odliczać.

Pomogło by to określić kiedy będzie można wykonać czynności takie jak:
- zakoncz (wiem, PvP-owcy nie polubią tej funkcji po drugiej stronie)
- otul sie plaszczem
- zaskocz
- zloz sztylet
- ziola (?)
- na coś jeszcze trzeba czekać?

**Comment by Stokrotka2** [comment]
Na zioła nie, ale aby kogoś zasłonić - tak.

**Comment by Delwing** [comment]
W pewnej formie zaimplementowane - wywołanie komendy wymagającej ochłonięcia wyświetla bind pod koniec czasu + na dole w pasku jest timer
