### ISSUE TITLE
Domyslne wskazywanie

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia#343]
Byłoby wygodnie, jeśli jest się prowadzącym drużyny, to komenda '/z' mogłaby zamiast 'zabij cel ataku' wykonywać to samo co '/z id' tylko zamist id przecinik.

Na expowiskach, gdzie są grupki takich samych wrogów nie ma znaczenia kogo się wskaże, więc można wejść na lokację, wpisać '/z' i drużyna leje pierwszego lepszego (tego co prowadzący).

**Comment by tjurczyk** [comment]
@filipbober ale prowadzacy moze widziec chyba innego przeciwnika jako pierwszego? GMCP nie jest raczej deterministyczne per gracza.

**Comment by Delwing** [comment]
Prowadzący też czasem ponawia atak na cel ataku, ja bym nie ruszał.
