### ISSUE TITLE
Herbowka

### ISSUE THREAD

**Issue by Walkir** [tjurczyk/arkadia#374]
Wiem, ze to juz bylo kilka razy walkowane ale nigdy tak na prawde nie zostalo naprawione.
Wszystkie gagi herbowki powinny zostac usuniete a zrobiona podmiana i wyswietlenie ze to spec.

Przykladowy gag do usuniecia tutaj:

`skrypty_master3 -> skrypty -> ui -> gags -> delete -> delete_moje_parowanie -> baron-tarcza2`

**Comment by tjurczyk** [comment]
A nie wyswietla, ze to spec?

```selectCurrentLine()
local str_replace = "[HERB SPEC] "
prefix(str_replace)
selectString(str_replace, 1)
fg(scripts.gag_colors["innych_ciosy"])
resetFormat()```

Tak mam w `baron-tarcza`, wiec powinno wyswietlac, ze to spec herbowki.

**Comment by tjurczyk** [comment]
U mnie to dziala poprawnie:

<img width="731" alt="screen shot 2018-09-30 at 10 55 42 am" src="https://user-images.githubusercontent.com/1749428/46260794-677eaf80-c49f-11e8-9fee-a454d6fc8bdb.png">

Gagi w `delete` nie sa uzywane jesli nie masz ich wlaczonych w opcjach. Mozesz dac screenshot co sie dzieje?

**Comment by Walkir** [comment]
Właśnie mam włączone, gaguje sobie wszystko co się da, więc nie ma co wklejać bo nic się nie dzieje, normalnie gaguje całą linikę.

**Comment by tjurczyk** [comment]
Nie rozumiem. Masz wlaczone delete? Wycinasz te teksty? Wciaz niestety nie rozumiem co jest problemem.

**Comment by Walkir** [comment]
`  ["moje_spece"] = 2,`

Myślałem, że tak długo jak moje spece są ustawione na widoczne to wszystkie spece, także te od broni/zbroi powinny też być widoczne. Nie wiem jak to jest kodowo na arce zrobione ale nie wydaje mi się żeby ten spec wchodził zamiast rzeczywistego parowania.

**Comment by tjurczyk** [comment]
@Walkir Mozesz dac mi dokladnego loga co jest nie tak? Chcialbym to w koncu poprawic jesli jest do poprawienia i zamknac.

**Comment by Delwing** [comment]
Raczej nie powinno być aktualne. Plus dodatkowo gagi #767
