### ISSUE TITLE
gzocen u nozownika

### ISSUE THREAD

**Issue by apolios** [tjurczyk/arkadia#377]
ocen sztylety stylizuje tekst i dodaje numerki, jednak uzycie gzocen tego nie robi. Ponizej tekst pojawiajacy sie po uzyciu komendy:

Dokladnie obracasz w dloniach czarny plomienisty sztylet i tileanski dlugi sztylet i nieznacznie przesuwajac palcem po ostrzach sprawdzasz ich stan.
Liczne slady walk wyryly na tileanskim dlugim sztylecie swoje pietno.
Czarny plomienisty sztylet jest w dobrym stanie.

**Comment by tjurczyk** [comment]
@apolios Mozesz podac przyklady roznic? To znaczy log: `ocen sztylety` vs `gzocen`. Potrzebuje wiedziec dokladnie jak wygladaja roznice.
@Senareil To samo do ulryka.

**Comment by apolios** [comment]
Przykladowo:
ocen sztylety:
`ocen sztylety

======= Oceniasz starannie czarny plomienisty sztylet. ========

Metal z ktorego wykonano ta bron ma dziwna, czarna barwe. Wydaje sie, iz sztylet pochlania kazdy
promien swiatla jaki padnie na jego powierzchnie, tak gleboka bowiem jest jego barwa. Ostrze 
sztyletu ma niezwykly, fascynujacy ksztalt... Ksztalt zakletego w metal plomienia, uchwyconego w 
jednej z poz swego smiertelnego, niszczycielskiego tanca. Po jego obrzezach pelzaja niebezpieczne 
blyski odbitego od ostrej stali, zielonkawego swiatla a pieknie wyprofilowana rekojesc zdobia trzy 
male, symetrycznie umieszczone szmaragdy.
Wyglada na to, ze jest w znakomitym stanie. [max]

Oceniasz, ze czarny plomienisty sztylet wazy 810 gramow, zas jego objetosc wynosi 300 mililitrow.
Wydaje ci sie, ze jest wart okolo 590 miedziakow, czyli 2 zl, 9 sr, 2 mdz.

 Typ broni: sztylet                Chwyt: w dowolnej rece            
 Obrazenia: klute i ciete                    
 Wywazenie: doskonale [12/14]      Skutecznosc: wyjatkowo skuteczne [12/14]          

======= Oceniasz starannie zakrzywiony waski sztylet. ========

Bogato przyzdobiona w delikatne wzory kosciana rekojesc, brak jelca, ostrze mocno zakrzywione,
stopione z dwoch roznych rodzajow stali - wszystko to wyroznia ten noz, od typowej broni karczemnych 
rzezimiechow. Jakosc wykonania i doskonale wywazenie nie pozostawiaja watpliwosci, jest to dzielo 
sztuki, tak jak i sztuka moze byc niejeden cichy mord dokonany ta smiertelna bronia.
Wyglada na to, ze jest w dobrym stanie. [6/7]

Oceniasz, ze zakrzywiony waski sztylet wazy 680 gramow, zas jego objetosc wynosi 370 mililitrow.
Wydaje ci sie, ze jest wart okolo 740 miedziakow, czyli 3 zl, 1 sr, 8 mdz.

 Typ broni: sztylet                Chwyt: w dowolnej rece            
 Obrazenia: klute i ciete                    
 Wywazenie: dobrze [10/14]         Skutecznosc: zabojczo skuteczne [13/14]        `

gzocen:
`Dokladnie obracasz w dloniach czarny plomienisty sztylet i tileanski dlugi sztylet i nieznacznie przesuwajac palcem po ostrzach sprawdzasz ich stan.
Liczne slady walk wyryly na tileanskim dlugim sztylecie swoje pietno.
Czarny plomienisty sztylet jest w dobrym stanie.`

**Comment by Senareil** [comment]
wuocen jest praktycznie skróconym, systemowo zakodowanym odpowiednikiem /sprzet. Ma tą przewagę, że nie musi pobierać z oceny, tylko bezpośrednio pobiera informację z itemu.

```
/sprzet
Umm, co chcesz ocenic?
Oceniasz starannie stalowy upiekszony helm z grzebieniem.
Jest to odlany z dobrej gatunkowo stali helm o lekko zaokraglonym, mieniacym sie srebrzyscie ksztalcie. Zbroja ta posiada masywny, ruchomy nosal, na tyle szeroki, ze w pozycji opuszczonej
zaslania takze policzki wojownika, pozostawiajac jednak mu wiele komfortu noszenia oraz nie ograniczajac pola widocznosci, co jest cenna zaleta w czasie zametu bitewnego. Wnetrze helmu zostalo 
wymoszczone miekka skora zapobiegajaca przed obiciem czaszki wlasciciela, natomiast jego gora pyszni sie wspanialym, przypominajacym koguci, czarnoczerwonym grzebieniem, z ktorego podstawy 
stercza na boki dwie krwistoczerwone kitki.
Wyglada na to, ze jest w znakomitym stanie. [max]

Oceniasz, ze stalowy upiekszony helm z grzebieniem wazy 7300 gramow, zas jego objetosc wynosi 1600 mililitrow.
Wydaje ci sie, ze jest wart okolo 510 miedziakow, czyli 2 zl, 2 sr, 6 mdz.
Zaklada sie go na glowe.
 Typ zbroi: ciezka                           Klute: dosc dobrze [8/12]               
 Ciete: dobrze [9/12]                        Obuchowe: dosc dobrze [8/12]            

======= Oceniasz starannie kolczasta stalowa tarcze. ========

Nie trzeba byc ekspertem, by rozpoznac, iz tarcza, na ktora spogladasz jest jedyna w swoim rodzaju. Boki jej okraglej powierzchni rozchodza sie w liczne grozne ostrza, lekko wygiete w kierunku
atakujacego. Slady zaschnietej krwi na niektorych z nich dowodza faktu, ze poprzedni wlasciciel potrafil wykorzystac atuty tej ochrony. Wykonana z solidnej stali czesc przyjmujaca sile 
uderzenia w pelni zakrywa przedramie, dlon i czesc bicepsu dzierzacego ja woja, spod zas wyscielony jest garbowana skora. Dwie skorzane petle, jak i poreczny uchwyt pomagaja rownomiernie 
rozlozyc ciezar, dajac pewnosc dobrej oslony, zas w przypadku mocnego ramienia sporej skutecznosci parowania ciosow.
Wyglada na to, ze jest lekko podniszczona. [4/5]

Oceniasz, ze kolczasta stalowa tarcza wazy 4100 gramow, zas jej objetosc wynosi 2300 mililitrow.
Wydaje ci sie, ze jest warta okolo 500 miedziakow, czyli 2 zl, 1 sr, 8 mdz.
Zalozona oslania jedno z ramion.
 Typ zbroi: tarcza                           Klute: przyzwoicie [6/12]               
 Ciete: doskonale [11/12]                    Obuchowe: przyzwoicie [6/12]            
 Parowanie: calkiem skuteczne [9/14]         

======= Oceniasz starannie tileanska lekka zbroje plytowa. ========

Polzbroja ta powstala w pracowniach tileanskich platnerzy. Sklada sie na nia kirys wraz z naramiennikami oraz przymocowanymi u dolu taszkami chroniacymi gorna czesc uda. Zbroja ta jest wygodna
w noszeniu i nie ogranicza ruchow, gdyz w calosci wykonano ja z waskich paskow stalowej blachy - folg zachodzacych na siebie od dolu i polaczonych przy pomocy skorzanych rzemieni i nitow.
Wyglada na to, ze jest w kiepskim stanie. [3/5]

Oceniasz, ze tileanska lekka zbroja plytowa wazy 14 kilogramow, zas jej objetosc wynosi 4300 mililitrow.
Wydaje ci sie, ze jest warta okolo 2500 miedziakow, czyli 10 zl, 8 sr, 4 mdz.
Zaklada sie ja na korpus, ramiona i nogi.
 Typ zbroi: ciezka                           Klute: dosc dobrze [8/12]               
 Ciete: dosc dobrze [8/12]                   Obuchowe: dosc dobrze [8/12]            
 Bronie, zbroje i ich stany

 stalowy upiekszony helm z grzebieniem -- [max] w znakomitym stanie.
 kolczasta stalowa tarcza ............ -- [4/5] lekko podniszczona.
 tileanska lekka zbroja plytowa ...... -- [3/5] w kiepskim stanie.
```

```
wuocen
Fachowym okiem osoby, ktora z doswiadczenia wie, jak wazna jest dobra zbroja i porzadna bron, dokonujesz przegladu swego ekwipunku.
Oceniasz tileanska lekka zbroje plytowa. Wyglada na to, ze jest w kiepskim stanie.
Oceniasz kolczasta stalowa tarcze. Wyglada na to, ze jest lekko podniszczona.
Oceniasz stalowy upiekszony helm z grzebieniem. Wyglada na to, ze jest w znakomitym stanie.
Z cichym skrzypnieciem widoczna w podlodze klapa zostaje podniesiona.
```
