### ISSUE TITLE
problem z mapperem przy większych drużynach

### ISSUE THREAD

**Issue by kociak1984** [tjurczyk/arkadia#395]
Problem zauważony dopiero teraz, jak trafiła się większa drużyna (>10 osób) - mapper gubi się i nie aktualizuje lokacji przy podążaniu za drużyną. Testowane na ostatnich trzech wersjach mudleta.

**Comment by tjurczyk** [comment]
@kociak1984 Czy mapper gubi sie na kazdej lokacji? czy jest to zawsze 10 lub wiecej osob? Mozesz podac loga z podazania z druzyna, z ktora sie gubi i jakies przykladowe lokacje?

**Comment by Delwing** [comment]
Nie zaobserwowane. Chodziłem w większych drużynach.
