### ISSUE TITLE
Dodanie nowej komendy do walki - zabij pozniej

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia#397]
Sytuacja. Wchodzimy na lokacje gdzie stoi sroga ekipa 2 trolli i 3 orkow. Prowadzacy na wejsciu daje 'zabij trolla' bo w sumie obojetne ktorego zaatakujemy na poczatku. Patrzac jednak na sytuacje wiadomo, ze kolejnym celem ataku po ubiciu pierwszego trolla bedzie drugi. Zatem by oszczedzic czas nie daloby sie moze dorobic komendy typu **/zp ID**, ktora fizycznie podlapie 'Obecny cel ataku padl' i z automatu wykona akcje zabij ID (modyfikowana przez obecny modyfikator przy ataku - czyli wskaze czy tez rozkaze). Ulatwiloby to ogarnianie prowadzacym expienie.

**Comment by tjurczyk** [comment]
Wydaje mi sie, ze samoistne klepanie `zabij ...` jest nielegalne, prawda?

**Comment by chlebik** [comment]
To chociaz bind?

**Comment by Delwing** [comment]
`/q` + `/nn`
