### ISSUE TITLE
Automatyczny bind na dobywanie broni na bagnach

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia#409]
Podczas walki z ghoulami na bagnach trucizna powoduje czasem opuszczenie broni. Niestety jedynym komunikatem jest: 'Nagle czujesz, jak dziwna sila opanowuje twe czlonki. Nie jestes w stanie kontrolowac swojego zachowania!'. Mysle, ze wtedy moznaby podpiac jednorazowego binda na 'dobadz broni'.

**Comment by tjurczyk** [comment]
https://github.com/tjurczyk/arkadia/pull/1462
