### ISSUE TITLE
Suby na cechy - gotowiec

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia#420]
Trzeba dodac epika i nadludzia (niestety nie mam jak sprawdzic) Wychodzi mniej wiecej tak:

                                                            
 ==>  [2/5] [   DUZO   ]  [X] [8/10] mocarny
 ==>  [2/5] [   DUZO   ]  [X] [8/10] akrobatyczny
 ==>  [3/5] [  TROCHE  ]  [X] [7/10] muskularny
 ==>  [2/5] [   DUZO   ]  [X] [6/10] bystry
 ==>  [2/5] [   DUZO   ]  [X] [6/10] dzielny

Perl regex:
(^Wydaje ci sie, ze (.*) ci brakuje, zebys (mogl|mogla) wyzej ocenic (swa|swoj) (sile|zrecznosc|wytrzymalosc|intelekt|odwage)\.$)

Code:
selectString("Wydaje ci sie, ze",1)
replace(" ==>")

selectString("ci brakuje, zebys mogl wyzej ocenic swa ",1)
replace(" [X] ")
selectString("ci brakuje, zebys mogl wyzej ocenic swoj ",1)
replace(" [X] ")

if matches[3] == "bardzo duzo" then 
selectString("bardzo duzo",1)
replace(" [1/5] [  B DUZO  ]")
end

if matches[3] == "duzo" then
selectString("duzo",1)
replace(" [2/5] [   DUZO   ]")
end
if matches[3] == "troche" then
selectString("troche",1)
replace(" [3/5] [  TROCHE  ]")
end
if matches[3] == "niewiele" then
selectString("niewiele",1)
replace(" [4/5] [ NIEWIELE ]")
end
if matches[3] == "bardzo niewiele" then
selectString("bardzo niewiele",1)
replace(" [5/5] [B NIEWIELE]")
end

if matches[6] == "sile" then
selectString(matches[6] ..".",1)
replace("".. CEsila)
end

if matches[6] == "zrecznosc" then
selectString(matches[6] ..".",1)
replace("".. CEZr)
end

if matches[6] == "wytrzymalosc" then
selectString(matches[6] ..".",1)
replace("".. CEWt)
end

if matches[6] == "intelekt" then
selectString(matches[6] ..".",1)
replace("".. CEInt)
end

if matches[6] == "odwage" then
selectString(matches[6] ..".",1)
replace("".. CEOdw)
end

Perl regex:
((^|^> )Jestes (.*), (.*), (.*), (.*) i (.*)\.$)

Code:
resetFormat()

selectString(matches[3].."Jestes",1)
replace("[XXX]")

if matches[4] == "slabiutki" or matches[4] == "slabiutka" then selectString(matches[4],1)replace(matches[4].." 1/10") CEsila = "[1/10] " .. matches[4] .. "" end
if matches[4] == "watly" or matches[4] == "watla" then selectString(matches[4],1)replace(matches[4].." 2/10") CEsila = "[2/10] " .. matches[4] .. "" end
if matches[4] == "slaby" or matches[4] == "slaba" then selectString(matches[4],1)replace(matches[4].." 3/10") CEsila = "[3/10] " .. matches[4] .. "" end
if matches[4] == "krzepki" or matches[4] == "krzepka" then selectString(matches[4],1)replace(matches[4].." 4/10") CEsila = "[4/10] " .. matches[4] .. "" end
if matches[4] == "silny" or matches[4] == "silna" then selectString(matches[4],1)replace(matches[4].." 5/10") CEsila = "[5/10] " .. matches[4] .. "" end
if matches[4] == "mocny" or matches[4] == "mocna" then selectString(matches[4],1)replace(matches[4].." 6/10") CEsila = "[6/10] " .. matches[4] .. "" end
if matches[4] == "potezny" or matches[4] == "potezna" then selectString(matches[4],1)replace(matches[4].." 7/10") CEsila = "[7/10] " .. matches[4] .. "" end
if matches[4] == "mocarny" or matches[4] == "mocarna" then selectString(matches[4],1)replace(matches[4].." 8/10") CEsila = "[8/10] " .. matches[4] .. "" end

if matches[5] == "nieskoordynowany" or matches[5] == "nieskoordynowana" then selectString(matches[5],1)replace(matches[5].." 1/10") CEZr = "[1/10] " .. matches[5] .. "" end
if matches[5] == "niezreczny" or matches[5] == "niezreczna" then selectString(matches[5],1)replace(matches[5].." 2/10") CEZr = "[2/10] " .. matches[5] .. "" end
if matches[5] == "niezgrabny" or matches[5] == "niezgrabna" then selectString(matches[5],1)replace(matches[5].." 3/10") CEZr = "[3/10] " .. matches[5] .. "" end
if matches[5] == "sprawny" or matches[5] == "sprawna" then selectString(matches[5],1)replace(matches[5].." 4/10") CEZr = "[4/10] " .. matches[5] .. "" end
if matches[5] == "zwinny" or matches[5] == "zwinna" then selectString(matches[5],1)replace(matches[5].." 5/10") CEZr = "[5/10] " .. matches[5] .. "" end
if matches[5] == "zreczny" or matches[5] == "zreczna" then selectString(matches[5],1)replace(matches[5].." 6/10") CEZr = "[6/10] " .. matches[5] .. "" end
if matches[5] == "gibki" or matches[5] == "gibka" then selectString(matches[5],1)replace(matches[5].." 7/10") CEZr = "[7/10] " .. matches[5] .. "" end
if matches[5] == "akrobatyczny" or matches[5] == "akrobatyczna" then selectString(matches[5],1)replace(matches[5].." 8/10") CEZr = "[8/10] " .. matches[5] .. "" end

if matches[6] == "cherlawy" or matches[6] == "cherlawa" then selectString(matches[6],1)replace(matches[6].." 1/10") CEWt = "[1/10] " .. matches[6] .. "" end
if matches[6] == "rachityczny" or matches[6] == "rachityczna" then selectString(matches[6],1)replace(matches[6].." 2/10") CEWt = "[2/10] " .. matches[6] .. "" end
if matches[6] == "mizerny" or matches[6] == "mizerna" then selectString(matches[6],1)replace(matches[6].." 3/10") CEWt = "[3/10] " .. matches[6] .. "" end
if matches[6] == "dobrze zbudowany" or matches[6] == "dobrze zbudowana" then selectString(matches[6],1)replace(matches[6].." 4/10") CEWt = "[4/10] " .. matches[6] .. "" end
if matches[6] == "wytrzymaly" or matches[6] == "wytrzymala" then selectString(matches[6],1)replace(matches[6].." 5/10") CEWt = "[5/10] " .. matches[6] .. "" end
if matches[6] == "twardy" or matches[6] == "twarda" then selectString(matches[6],1)replace(matches[6].." 6/10") CEWt = "[6/10] " .. matches[6] .. "" end
if matches[6] == "muskularny" or matches[6] == "muskularna" then selectString(matches[6],1)replace(matches[6].." 7/10") CEWt = "[7/10] " .. matches[6] .. "" end
if matches[6] == "atletyczny" or matches[6] == "atletyczna" then selectString(matches[6],1)replace(matches[6].." 8/10") CEWt = "[8/10] " .. matches[6] .. "" end

if matches[7] == "bezmyslny" or matches[7] == "bezmyslna" then selectString(matches[7],1)replace(matches[7].." 1/10") CEInt = "[1/10] " .. matches[7] .. "" end
if matches[7] == "tepy" or matches[7] == "tepa" then selectString(matches[7],1)replace(matches[7].." 2/10") CEInt = "[2/10] " .. matches[7] .. "" end
if matches[7] == "ograniczony" or matches[7] == "ograniczona" then selectString(matches[7],1)replace(matches[7].." 3/10") CEInt = "[3/10] " .. matches[7] .. "" end
if matches[7] == "pojetny" or matches[7] == "pojetna" then selectString(matches[7],1)replace(matches[7].." 4/10") CEInt = "[4/10] " .. matches[7] .. "" end
if matches[7] == "inteligentny" or matches[7] == "inteligentna" then selectString(matches[7],1)replace(matches[7].." 5/10") CEInt = "[5/10] " .. matches[7] .. "" end
if matches[7] == "bystry" or matches[7] == "bystra" then selectString(matches[7],1)replace(matches[7].." 6/10") CEInt = "[6/10] " .. matches[7] .. "" end
if matches[7] == "blyskotliwy" or matches[7] == "blyskotliwa" then selectString(matches[7],1)replace(matches[7].." 7/10") CEInt = "[7/10] " .. matches[7] .. "" end
if matches[7] == "genialny" or matches[7] == "genialna" then selectString(matches[7],1)replace(matches[7].." 8/10") CEInt = "[8/10] " .. matches[7] .. "" end

if matches[8] == "tchorzliwy" or matches[8] == "tchorzlowa" then selectString(matches[8],1)replace(matches[8].." 1/10") CEOdw = "[1/10] " .. matches[8] .. "" end
if matches[8] == "strachliwy" or matches[8] == "strachliwa" then selectString(matches[8],1)replace(matches[8].." 2/10") CEOdw = "[2/10] " .. matches[8] .. "" end
if matches[8] == "niepewny" or matches[8] == "niepewna" then selectString(matches[8],1)replace(matches[8].." 3/10") CEOdw = "[3/10] " .. matches[8] .. "" end
if matches[8] == "zdecydowany" or matches[8] == "zdecydowana" then selectString(matches[8],1)replace(matches[8].." 4/10") CEOdw = "[4/10] " .. matches[8] .. "" end
if matches[8] == "odwazny" or matches[8] == "odwazna" then selectString(matches[8],1)replace(matches[8].." 5/10") CEOdw = "[5/10] " .. matches[8] .. "" end
if matches[8] == "dzielny" or matches[8] == "dzielna" then selectString(matches[8],1)replace(matches[8].." 6/10") CEOdw = "[6/10] " .. matches[8] .. "" end
if matches[8] == "nieugiety" or matches[8] == "nieugieta" then selectString(matches[8],1)replace(matches[8].." 7/10") CEOdw = "[7/10] " .. matches[8] .. "" end
if matches[8] == "nieustraszony" or matches[8] == "nieustraszona" then selectString(matches[8],1)replace(matches[8].." 8/10") CEOdw = "[8/10] " .. matches[8] .. "" end

**Comment by Delwing** [comment]
Już zrobione
