### ISSUE TITLE
states_window

### ISSUE THREAD

**Issue by Ichaero** [tjurczyk/arkadia#468]
Okienko kondycji ma czarne tło tak jak reszta pól. Ja mam je na wierzchu jako "pływające" i wtedy zlewa się z głównym oknem. Czy dałoby się: a) dodać możliwość zmiany koloru tła w states_window? lub b) dodanie do states_window jakichś ramek?

**Comment by efski** [comment]
Moglbys dodac mozliwosc rodzielenia okna statusu na 2, tak by w jednym byla tylko kondycja druzyny, w drugim wrogow/wszystkich? Uzywanie komend kondycja druzyny dodatkowo wyswietla  postaci w kolejnosci dolaczenia do druzyny, a nie przybycia na lokacje.

**Comment by Delwing** [comment]
2 wprowadzone, pierwsze można sobie dodać w razie potrzeby we własnym zakresie.
