### ISSUE TITLE
Brakujący ogłuch

### ISSUE THREAD

**Issue by Ichaero** [tjurczyk/arkadia#469]
Szkaradny czarnobrody pukacz pochyla kosmaty leb i rzuca sie do przodu, z
pelnym impetem trafiajac wprost w ciebie. Uderzenie w glowe oglusza cie i powala na ziemie.

Zarosniety warkliwy pukacz pochyla kosmaty leb i rzuca sie do przodu, z pelnym impetem trafiajac w XXX. Uderzenie oglusza i powala ofiare.

**Comment by Ichaero** [comment]
Kolejne do dodania:

XXX znienacka kopie YYY w noge i kiedy ten traci rytm walki, przywala mu
piescia prosto w nos.

XXX znienacka kopie cie w noge i kiedy tracisz rytm walki, przywala ci
piescia prosto w nos.

Ktos bez zastanowienia uderza cie piescia w szczeke, robiac to z taka sila, ze niemal powala cie na ziemie.

**Comment by Delwing** [comment]
A to do zamknięcia też, bo dodane.
