### ISSUE TITLE
Bindowanie otwierania bram po opisie.

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#474]
Na chwile obecną, dopiero nieudana próba przejścia przez bramę, aktywuje binda otwierania bramy.
Nawet jak stanąć przed zamkniętą i dać otwieranie CRTL + B, to nie otwiera.
Dopiero wejście w bramę aktywuje CTRL+B do otworzenia.

Probujesz otworzyc okute wrota, ale nie udaje ci sie to.
[bind CTRL + B] Otworz brame

Zamknieta stalowa krata prowadzaca na zachod.
Otwarta stalowa krata prowadzaca na wschod.
Zamknieta stalowa krata prowadzaca na poludnie.

Zamkniete okute wrota prowadzace na wschod.
Otwarte okute wrota prowadzace na zachod.
Zamkniete okute wrota prowadzace na poludniowy-zachod.
Zamkniete okute wrota prowadzace na wschod.

**Comment by Delwing** [comment]
`/brama` rozwiazuje ten problem
