### ISSUE TITLE
powiekszenie odstepow w pasku donlym

### ISSUE THREAD

**Issue by ardberg** [tjurczyk/arkadia#477]
Hej,

ustawianie odstepow (lub powiekszenie) na pasku dolnym,
np Zabici jesli nabije sie trzy cyfrowe nie mieszcza sie.

![image](https://user-images.githubusercontent.com/63424797/78935877-7d622d00-7aa5-11ea-8492-eb5b7d6925b0.png)

**Comment by Delwing** [comment]
To już jest poprawione.
