### ISSUE TITLE
Propozycja zmiana koloru przy przełamaniu naszej ochrony.

### ISSUE THREAD

**Issue by ctarx** [tjurczyk/arkadia#480]
W obecnej formie przełamanie zasłony przez kogoś wyświetla się na zielono. Proponuję wyróżnić przełamanie naszej ochrony na inny kolor, ponieważ w tym przypadku kolor zielony jest mylący.

**Comment by ctarx** [comment]
Wyróżniłbym wszystkie ataki na nas:
`(Zrecznie zaslaniasz|Na rozkaz .* zaslaniasz) .*`
`.* zagradzasz .* droge.*`
`.* szybko przesuwa sie za ciebie, kryjac sie przed .*`
`.* rzuca sie do ataku na ciebie!`
`.* wykorzystujac zaskoczenie przebija sie przez twoja ochrone.`
`.* atakuje cie!`
`.* rzuca sie na ciebie przebijajac sie przez twoja ochrone.`

**Comment by mwarzec** [comment]
Popieram.

**Comment by Delwing** [comment]
przełamania przez członków drużyny są na zielono, reszta na czerwono.
