### ISSUE TITLE
Walka wiedzmińskim mieczem

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#511]
Nie podaje siły ciosu

Chwytasz prawa reka za podkrzyze swego srebrnego wiedzminskiego miecza dwurecznego, by wykonac nim blyskawiczne pchniecie, mierzac w leb ogromnej drapieznej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak muskajac.

Chwytasz lewa reka za podkrzyze swego srebrnego wiedzminskiego miecza dwurecznego, by wykonac nim blyskawiczne ciecie, mierzac w leb duzej zwinnej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak muskajac.

Chwytasz prawa reka za podkrzyze swego srebrnego wiedzminskiego miecza dwurecznego, by wykonac nim blyskawiczne pchniecie, mierzac w leb duzej zwinnej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak muskajac.

Zła siła ciosu
[3/6] Dostrzegajac szanse na skuteczny atak na ogromna drapiezna endriage, chwytasz srebrny wiedzminski miecz dwureczny za podkrzyze i wykonujesz serie szybkich ciec i pchniec, z ktorych kazde rani i wyraznie meczy przeciwniczke. Po tym skutecznym porywie dajesz sobie chwile na odpoczynek, podczas ktorej wygodnie ukladasz obie rece na rekojesci swego oreza, szykujac sie do ostatecznego natarcia. Gdy jestes juz gotow, w odpowiedniej chwili poteznym wymachem wyprowadzonym z calego ciala wbijasz ostrze broni w tulow wroga. Ofiara wali sie bezwladnie na ziemie, tobie zas pozostaje wyrwac zaklinowany miecz, gdyz walka ta juz sie zakonczyla.
Ogromna drapiezna endriaga umarla.

[3/6] Dostrzegajac szanse na skuteczny atak na ogromna zwinna endriage, chwytasz srebrny wiedzminski miecz dwureczny za podkrzyze i wykonujesz serie szybkich ciec i pchniec, z ktorych kazde rani i wyraznie meczy przeciwniczke. Po tym skutecznym porywie dajesz sobie chwile na odpoczynek, podczas ktorej wygodnie ukladasz obie rece na rekojesci swego oreza, szykujac sie do ostatecznego natarcia. Gdy jestes juz gotow, w odpowiedniej chwili poteznym cieciem zza glowy 
rabiesz wroga, zaglebiajac polowe szerokosci ostrza broni w jej tulow. Ofiara wali sie bezwladnie na ziemie, tobie zas pozostaje wyrwac zaklinowany miecz, gdyz walka ta juz sie zakonczyla.
Ogromna zwinna endriaga umarla.

Coś takiego jakby urywało w logu
16:46:13.595 Chwytasz prawa reka za podkrzyze swego srebrnego wiedzminskiego miecza dwurecznego, by wykonac nim blyskawiczne
16:46:13.595 pchniecie, mierzac w tulow olbrzymiej agresywnej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak 
16:46:13.595 muskajac.
16:46:17.861 mierzac w leb olbrzymiej agresywnej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak muskajac.

16:47:21.620 Chwytasz lewa reka za podkrzyze swego srebrnego wiedzminskiego miecza dwurecznego, by wykonac nim blyskawiczne ciecie,
16:47:21.620 mierzac w tulow ogromnej drapieznej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak muskajac.
16:47:25.599 uderzyc nim w ogromna drapiezna endriage. Precyzyjny cios tnie przeciwniczke prosto w tulow, pozostawiajac lekkie rany.

16:47:52.599 Duza agresywna endriaga doskakuje sprawnie do ciebie i zanurza niegroznie ostre zeby w twojej szyi!
16:47:59.816 uderzyc nim w duza agresywna endriage. Precyzyjny cios tnie przeciwniczke prosto w tulow, pozostawiajac lekkie rany.
16:48:00.039 Duza agresywna endriaga jest w zlej kondycji.

16:52:41.325 [2/7] Wykonujesz zwinny polobrot, ciagnac sztych swego srebrnego wiedzminskiego miecza dwurecznego tuz za soba by
16:52:41.325 uderzyc nim w olbrzymia zwinna endriage. Precyzyjny cios tnie przeciwniczke prosto w tulow, pozostawiajac lekkie rany.
16:52:41.710 [1/6] Ogromna drapiezna endriaga ledwo muska cie prawa lapa, trafiajac cie w korpus.
16:52:44.889 mierzac w prawa lape olbrzymiej zwinnej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak muskajac.
16:52:48.517 [2/7] Wykonujesz nagle pchniecie swym srebrnym wiedzminskim mieczem dwurecznym, lekko raniac olbrzymia zwinna endriage w
16:52:48.517 leb.

**Comment by tjurczyk** [comment]
@mwarzec A masz sily ciosow do kazdego z opisow? Bo bez tego nie jest mozliwym dodanie ich.

**Comment by mwarzec** [comment]
1. Chwytasz prawa reka za podkrzyze swego srebrnego wiedzminskiego miecza dwurecznego, by wykonac nim blyskawiczne
pchniecie, mierzac w leb olbrzymiej zwinnej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak 
muskajac.

Chwytasz lewa reka za podkrzyze swego srebrnego wiedzminskiego miecza dwurecznego, by wykonac nim blyskawiczne
ciecie, mierzac w tulow olbrzymiej zwinnej endriagi. Cios trafia zaskoczona przeciwniczke, zaledwie ja jednak 
muskajac.


7 - finish 
Dostrzegajac szanse na skuteczny atak na olbrzymia zwinna endriage, chwytasz srebrny wiedzminski miecz dwureczny
za podkrzyze i wykonujesz serie szybkich ciec i pchniec, z ktorych kazde rani i wyraznie meczy przeciwniczke. Po 
tym skutecznym porywie dajesz sobie chwile na odpoczynek, podczas ktorej wygodnie ukladasz obie rece na rekojesci 
swego oreza, szykujac sie do ostatecznego natarcia. Gdy jestes juz gotow, w odpowiedniej chwili poteznym wymachem 
wyprowadzonym z calego ciala wbijasz ostrze broni w leb wroga. Ofiara wali sie bezwladnie na ziemie, tobie zas 
pozostaje wyrwac zaklinowany miecz, gdyz walka ta juz sie zakonczyla.

unik - nie gaguje
Chwytasz prawa reka za podkrzyze swego srebrnego wiedzminskiego miecza dwurecznego, by wykonac nim blyskawiczne
ciecie, mierzac w tulow ogromnej agresywnej endriagi. Przeciwniczka w pore orientuje sie jednak w twych zamiarach 
i zwinnie unika ataku.

**Comment by tjurczyk** [comment]
Z tego co wiem juz dodane. Jesli wciaz ktorychs brakuje, otworz ponownie
