### ISSUE TITLE
Zmienna globalnego licznika postepow!

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia#529]
Znajdźcie w kodzie tabeli zdobytych postępów "/postepy2"

`sum = sum + v["val"]`

i zamieńcie na:
```
sum = sum + v["val"]
CalkowiteDoLvla = sum
```

Nie mogę tego znaleźć u siebie, a to wyciąga bardzo ważną liczbę dla mnie, czyli sumę globalnie zdobytych postępów!

**Comment by Delwing** [comment]
To nie powinno być implementowane w ten sposób.
