### ISSUE TITLE
Wtyczki do skryptów

### ISSUE THREAD

**Issue by filipbober** [tjurczyk/arkadia#561]
Niektórzy tworzą bardzo przydatne wtyczki (jak na przykład wtyczka napisana przez airma), które niekoniecznie powinny być domyślnie włączone w defaultowych skryptach.

Przydałby się osobny folder 'plugins' obok 'mapper', 'skrypty' i 'sounds' na takie właśnie wtyczki. Każda wtyczka miałaby osobny podfolder w katalogu 'plugins' wraz z obowiązkowym plikiem README.md z opisem co dana wtyczka robi, jak ją włączyć i jak ją wyłączyć.

Wszystkie zasoby danej wtyczki: skrypty, dźwięki, obrazki byłyby przechowywane w katalogu danej wtyczki.

**Comment by Delwing** [comment]
Jest to w planach, nawet mam kawałek kodu napisany pod to.
Wtyczka musiałaby po prostu przestrzegać pewnej konwencji, żeby było możliwe automatyczne jej załadowanie.

**Comment by Delwing** [comment]
Obsługa dodana.

**Comment by filipbober** [comment]
Super, dzięki
