### ISSUE TITLE
Zaproszenie od ukrytego.

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#587]
Nie działa bindowanie, gdy osoba zapraszajaca do druzyny jest ukryta. 
Pewnie przez nawiasiki [ ] 

[XXXXX] zaprasza cie do swojej druzyny.

**Comment by Delwing** [comment]
Jaki numer wersji?

**Comment by Delwing** [comment]
Sprawdzone dzisiaj. Działa. Sprawdź czy masz najnowszą wersję.
