### ISSUE TITLE
Blokowanie ruchu przy przeszukiwaniu

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#598]
Są lokacje / itemy z różnymi efektami przeszukania...

Zaczynasz przeszukiwac XXX.
-- Zaczyna działać blokowanie ruchu na mapie.

Efekty są różne przeszukiwania...
Za jednym ze zdobiacych sciany sztandarow znajdujesz ukryta dzwignie.
W plytkiej niszy w rogu komnaty znajdujesz ukryta dzwignie.
itp

Sugeruje zrobić odblokowywanie na timerze. Po 4-5 sekundach od rozpoczecia przeszukiwania powinno odblokowac mozliwosc ruchu. Teraz z palca niby wpisuje aby odblokowac:  /mm follow

**Comment by Delwing** [comment]
Myślę, że zgodnie z rozmowami nie będziemy tego implementować.
