### ISSUE TITLE
Zioła - dodanie nowych do bazy i zła odmiana ziół

### ISSUE THREAD

**Issue by newidyn** [tjurczyk/arkadia#632]
Urzet źle się odmienia w bazie lub źle czyta. Zamiast "wez niepozorne sinozielona roslinki z otwartego woreczka" powinno brać "wez niepozorna sinozielona roslinke z otwartego woreczka".

Można dodać do bazy ciemny gruzlowaty grzyb -skedar.
    "skedar": {
      "mianownik": "ciemny gruzlowaty grzyb",
      "dopelniacz": "ciemnego gruzlowatego grzyba",
      "biernik": "ciemny gruzlowaty grzyb",
      "mnoga_mianownik": "ciemne gluzowate grzyby",
      "mnoga_dopelniacz": "ciemnych gruzlowatych grzybow",
      "mnoga_biernik": "ciemne gruzlowate grzyby"
    },

    "skedar": [
      {
        "action": "zjedz",
        "effect": "?"
      }
    ]

**Comment by tjurczyk** [comment]
@newidyn Jestes pewien, ze masz najnowsze skrypty? Baza ziol sciaga sie po otwarciu Mudleta i zaladowaniu skryptow.

Aktualna wersja:

```
1003     "urzet": {
1004       "mianownik": "niepozorna sinozielona roslinka",
1005       "dopelniacz": "niepozornej sinozielonej roslinki",
1006       "biernik": "niepozorna sinozielona roslinke",
1007       "mnoga_mianownik": "niepozorne sinozielone roslinki",
1008       "mnoga_dopelniacz": "niepozornych sinozielonych roslinek",
1009       "mnoga_biernik": "niepozorne sinozielone roslinki"
1010     },
```

Skedar tez juz jest dodany.

**Comment by newidyn** [comment]
Jak zainstaluje wersje z mastera to działa i branie urzetu i czyta skedar, ale wersja 4.7 (pobiera przez aktualizuj_skrypty) ma wciąż błędne branie urzetu i mimo skedara w bazie herbs_data nie buduje z nim bazy ziół.

**Comment by newidyn** [comment]
Jeszcze jedno zauważyłam : przy odmianie pięciornika jest błąd. W mnogim dopełniaczu jest napisane "ciemnych poskrecanych klacz", a powinno być "ciemnych poskrecanych klaczy".

**Comment by tjurczyk** [comment]
> Jeszcze jedno zauważyłam : przy odmianie pięciornika jest błąd. W mnogim dopełniaczu jest napisane "ciemnych poskrecanych klacz", a powinno być "ciemnych poskrecanych klaczy".

Dzieki, poprawione

> Jak zainstaluje wersje z mastera to działa i branie urzetu i czyta skedar, ale wersja 4.7 (pobiera przez aktualizuj_skrypty) ma wciąż błędne branie urzetu i mimo skedara w bazie herbs_data nie buduje z nim bazy ziół.

czyli wszystko ok - zapewniamy dzialanie skryptow tylko w najnowszej wersji :)
