### ISSUE TITLE
Brak opisu ogłuszenia?

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#638]
W pliku imie:
["ogluchy"] = 2

I w czasie walki nie pokazał się opis ciosu, który ogłuszył.

[1/6] Ulav ledwo muska cie smuklym grawerowanym nadziakiem bojowym, trafiajac cie w korpus.
Mloda porywcza gnomka (Scoja SC) jest w dobrym stanie. Atakujesz ja ty i Ertrand.
Jestes w pelni wypoczety.
[ N ZASLANIA ] Grozny siwy krasnolud probuje zaslonic mloda porywcza gnomke przed twoimi ciosami, jednak nie jest w 
stanie tego uczynic.

[   OGLUCH   ] ----- JESTES OGLUSZONY -----

Jestes w dobrym stanie.
[1/6] Ktos ledwo muska cie obosiecznym gwiezdnym toporem, trafiajac cie w prawe ramie.
[ N ZASLANIA ] Ktos probuje zaslonic cie przed ciosami kogos, jednak nie jest w stanie tego uczynic.

[  ZASLANIA  ] Ktos zrecznie zaslania kogos przed twoimi ciosami.

Ktos wykonujac ukosny zamach dlugim runicznym korbaczem trafiaja cie w prawe ramie, dotkliwie raniac.
[2/6] Ktos lekko rani cie smuklym grawerowanym nadziakiem bojowym, trafiajac cie w glowe.
Jestes lekko ranny.

[   OGLUCH   ] ----- KONIEC OGLUCHA -----

**Comment by Delwing** [comment]
`ogluchy = 1` będzie usuwało linię z opisem
`ogluchy = 2` podmienia linię na ww. więc wszystk ok
