### ISSUE TITLE
Aliasy bez podania argumentow (jesli ich wymagaja) moglyby wyswietlac pomoc do tych aliasow 

### ISSUE THREAD

**Issue by Dranjam** [tjurczyk/arkadia#649]
Czyli np. /spe_lok bez argumentu wyswietli:

| /spe_lok [kierunek] [specjalne przejscie] - dodaje lokacje w kierunku          |
| [kierunek], na ktora przechodzi sie komenda [specjalne przejscie]              |
| przykladowo: '/spe_lok e przejdz przez strumien' stworzy lokacje na wschod (e) |
| od aktualnej, na ktora przechodzi sie przejsciem 'przejdz przez strumien'.     |

Szczególnie przydatne w aliasach mappera, gdzie jest wiele różnych aliasów, które łatwo się mylą.

Pozdrawiam!

**Comment by Delwing** [comment]
Tak jak pomysł dobry, to stosunkowo dużo zabawy, dla stosunkowo niewielkiej korzyści.
