### ISSUE TITLE
pominięte off_pausers

### ISSUE THREAD

**Issue by artakserkses** [tjurczyk/arkadia#659]
Hej, zakładam issue dla pominiętych off_pauserów, jak coś znajdę, to będę tutaj doklejał 👍 
Póki co:
Niestety nic takiego tu nie ma.

Jakby dało nie zamykać całego issue, tylko zaznaczać, które pausery już są dodane (albo i nawet tego nie :D) to będę dźwięczny

**Comment by artakserkses** [comment]
Przeszukujesz legowisko znajdujac tam ...
i chyba zamiast legowisko może też być leze i inne podobne :)

**Comment by Dranjam** [comment]
<ktos> zagradza ci droge.

**Comment by artakserkses** [comment]
Miedzy obsydianowymi soplami zauwazasz ukryte drzwi.
