### ISSUE TITLE
Brakujące magiki

### ISSUE THREAD

**Issue by artakserkses** [tjurczyk/arkadia#667]
okragly migotliwy puklerz

**Comment by Delwing** [comment]
Masz go jeszcze? Warto zawsze wrzucić wynik 'odmien puklerz` to nie bedziemy sami musieli sobie przypominac odmiany przez przypadki ;)

**Comment by artakserkses** [comment]
Okragly migotliwy puklerz odmienia sie nastepujaco:

  Mianownik: okragly migotliwy puklerz,
 Dopelniacz: okraglego migotliwego puklerza,
   Celownik: okraglemu migotliwemu puklerzowi,
    Biernik: okragly migotliwy puklerz,
  Narzednik: okraglym migotliwym puklerzem,
Miejscownik: okraglym migotliwym puklerzu.

Rozpoznawane nazwy: puklerz, tarcza i zbroja.
