### ISSUE TITLE
Dodanie nowej "gildii" do bazy

### ISSUE THREAD

**Issue by Dranjam** [tjurczyk/arkadia#704]
Proszę o rozważenie dodania dodatkowego znacznika gildii do bazy "NM" lub "ENM" lub innego, do "gildii" tej moglyby być dodawane osoby zidentyfikowane jako wrogie, jednak nie przynależące do stowarzyszeń, lub o nieokreślonej przynależności.

Obecnie takie osoby celem oznaczania ich jako wroga muszą być przypisane do któregoś z istniejących stowarzyszeń, co prowadzi do bałaganu i ogólnego zamieszania.

**Comment by Delwing** [comment]
`scripts.people.enemy_people` pozwala dodawać osoby jako wrogie, bez ingerencji w stowarzyszenie.
