### ISSUE TITLE
Kategoryzacja

### ISSUE THREAD

**Issue by Delwing** [tjurczyk/arkadia#713]
talwar
gnomie obrotowe dluto, lekki skavenski pejcz i gietki pokutny kanczug
sygnet
całun

łapie jako kamienie
przezroczysta obraczke z krysztalu          
bezbarwny potrojny sznur bialych perel

łapie jako tarcze
sklerotyzowanych mlecznoszarych tarczek

łapie jako korpus
nakrapiany chitynowy pancerz

**Comment by thaerro** [comment]
Brak kategorii:

spizowa ponacinana spisa (bron drzewcowa)
luskowa pancerna skorupa zolwia (tarcza)
biale zdobione parazonium (sztylet)
 stalowy czerniony klobuk (helm)
dlugi czerniony lancuch (maczuga)
metalowy solidny kropacz (maczuga)
