### ISSUE TITLE
Dodanie broni w pochwie/temblaku do komendy /sprzet

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia#736]
Wychodzi mi, że komenda '/sprzet' nie ocenia broni schowanej w pochwie/temblaku. Trzeba by ją wyjąć, ocenić i schować ponownie.

**Comment by Delwing** [comment]
Sama arkadia nie oceni sprzętu w temblaku/pochwie. Jeżeli potrzebujesz oceny tych przedmiotów musisz niestety je wyciągnąć. Tak samo jak i z plecaka.
