### ISSUE TITLE
Wstawanie w niektórych miejscach nie odblokowuje mappera

### ISSUE THREAD

**Issue by kociak1984** [tjurczyk/arkadia#737]
Zauważone w karczmie w osadzie elfiej w Aedirn, oraz przy zeskakiwaniu z hamaka: Mapper zostaje zablokowany i mimo ustawiania nowej lokalizacji zostaje w konkretnym miejscu i przestaje podążać za postacią.

**Comment by Delwing** [comment]
Jest to możliwe, potrzebny jest konkretny tekst wstawania, dodamy.

**Comment by kociak1984** [comment]
Mea culpa, po aktualizacji w osadzie odblokowuje się poprawnie. Zostaje hamak.
Przykład hamaka:
`Zeskakujesz z rozwieszonego plociennego szerokiego hamaka.`
Jeśli coś jeszcze wyłapię to dodam tu.
