### ISSUE TITLE
Złe zliczanie globalnych postępów

### ISSUE THREAD

**Issue by chlebik** [tjurczyk/arkadia#766]
Nie wiem czy mechanizm nie został zaimplementowany poprawnie, czy problemem jest brak czyszczenia jakiś zmiennych , ale grając na przemian dwiema postaciami (i wyłączając komputer po drodze) - globalne postępy pod komendą '/postepy2' nabijają się 'wspólnie'. Zakładam, że stan jest trzymany globalnie pewnie.

Kiedyś taki błąd zgłaszałem przy depozytach i zostało to naprawione (każda postać ma oddzielne).

**Comment by Delwing** [comment]
Czy każda z postaci ma swój config z imienie postaci w konfiguracji?

**Comment by chlebik** [comment]
Aaaaargh. Nie, nie mają.

HINT:  Głupi błąd bo w JSONie (przynajmniej u mnie), zaraz na początku configu jest "amap.locating.name" gdzie jest wpisane imię poprawne, ale to, co jest ważne (czyli scripts.character_name) jest niżej i tam jest wartość dla innej postaci (której plik konfiguracyjny był bazą dla nowej).

Nie pamiętam czy to robiłem ręcznie, czy to wyszło ze skryptu migrującego, ale może by uniknąć głupich błędów dałoby się tak ustawić wzorcowy plik konfigu/skrypty migrujące by 'scripts.character_name' wylądowało na górze pliku?
