### ISSUE TITLE
Ocena broni wywala blad

### ISSUE THREAD

**Issue by Aruccio** [tjurczyk/arkadia#780]
gdy jest jej za duzo. 32 nie wywalilo, 48 tak. Coś takiego:

`
======= Oceniasz starannie czarna dluga wlocznie. ========

Na dlugim, jesionowym drzewcu osadzony jest smukly grot wykonany z dziwnego, czarnego
metalu. Wlocznia pozbawiona jest wszelkich zdobien i upiekszen. Prosta, wytrzymala i 
smiertelnie skuteczna we wprawnych dloniach.
Wyglada na to, ze jest w znakomitym stanie. [max]

Oceniasz, ze czarna dluga wlocznia wazy 5500 gramow, zas jej objetosc wynosi 1900
mililitrow.
Wydaje ci sie, ze jest warta okolo 330 miedziakow, czyli 1 zl, 7 sr, 6 mdz.

 Typ broni: bron drzewcowa                   Chwyt: w dowolnej rece                      
 Obrazenia: klute                            
 Wywazenie: perfekcyjnie [13/14]             Skutecznosc: bardzo skuteczne [10/14]       

 Suma: 23                                    Srednia: 11.5                               

======= Oceniasz starannie skrzaca kamienna wlocznie. ========

mpldG9zYyB3eW5vc2kgMTkwMCBtaWxpbGl0cm93LgpXeWRhamUgY2kgc2llLCB6ZSBqZXN0IHdhcnRhIG9rb2xvIDg
2MCBtaWVkemlha293LgoKWmF1d2F6YXN6LCBpeiBnbGV3aWEgamVzdCBwcnp5c3Rvc293YW5hIGRvIGNod3l0YW5pY
SBvYnVyYWN6LgpaYSBqZWogcG9tb2NhIG1vem5hIHphZGF3YWMgcmFueSBrbHV0ZSBpIGNpZXRlLgpUd29qZSBkb3N
3aWFkY3plbmllIGkgdW1pZWpldG5vc2NpIHBvZHBvd2lhZGFqYSBjaSwgemUgamFrIG5hIGJyb24gZHJ6ZXdjb3dhI
Gplc3Qgb25hIGRvc2MgZG9icnplIHd5d2F6b25hIGkgbmllend5a2xlIHNrdXRlY3puYS4K","type":"object.lo
ng"}GFqZSBjaSBzaWUsIHplIGplc3Qgd2FydGEgb2tvbG8gMTEwMCBtaWVkemlha293LgoKWmF1d2F6YXN6LCBpeiB
uYWdpbmF0YSBqZXN0IHByenlzdG9zb3dhbmEgZG8gY2h3eXRhbmlhIG9idXJhY3ouClphIGplaiBwb21vY2EgbW96b
mEgemFkYXdhYyByYW55IGtsdXRlIGkgY2lldGUuClR3b2plIGRvc3dpYWRjemVuaWUgaSB1bWllamV0bm9zY2kgcG9
kcG93aWFkYWphIGNpLCB6ZSBqYWsgbmEgYnJvbiBkcnpld2Nvd2EgamVzdCBvbmEgYmFyZHpvIGRvYnJ6ZSB3eXdhe
m9uYSBpIHd5amF0a293byBza3V0ZWN6bmEuCg==","type":"object.long"}Oceniasz starannie skrzaca 
kamienna wlocznie.`

**Comment by Delwing** [comment]
Problem jest wyłącznie związany z Mudletem, nie ze skryptami. Test na profilu bez skryptów z `gmcp wlacz modul gmcp_msgs` daje identyczny rezultat.

Zgłoszone.
https://github.com/Mudlet/Mudlet/issues/4385

Tutaj zamykam.
