### ISSUE TITLE
Lasek z hobgoblinami - cofanie mapy

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#807]
Przyszedłem z SW, ide na W gdzie nie ma wyjścia.

"Ruszasz razno na zachod, lecz po kilku krokach grzezniesz w krzakach."
Cofa mnie na mapie na NE.

Powinno brać opis w którą stronę nie mogę iść i cofać w przeciwną na mapie.

**Comment by Delwing** [comment]
Nie obserwuje takiego zachowania, mapper cofa mi poprawnie zarówno na opcji 
`/cset amap.blockers.is_experimental=false` jak i `/cset amap.blockers.is_experimental=true`
Może coś jeszcze masz w skryptach? jakaś duplikacja, że cofa Cię dwa razy.
