### ISSUE TITLE
Wyróżnianie efektu zioła

### ISSUE THREAD

**Issue by thaerro** [tjurczyk/arkadia#809]
Cześć,
Czy można dodać wyróżnienie efektu działania zioła? Jakiś kolor?

na przykład takich:
Czujesz sie mniej odporny na trucizne.
Czujesz sie bardziej odporny na trucizne.
Czujesz sie wytrzymalszy.
itp.

Oczywiście pamiętajmy o rodzaju żeńskim. :)

**Comment by Delwing** [comment]
Jakby ktoś je spisał wszystkie to dałoby radę -> można to spiąć z kolorkami efektu z bazy, żeby były jednolite.

**Comment by thaerro** [comment]
To co mam: :)

```
Czujesz sie zreczniejszy.
Czujesz sie bardziej niezdarny.

Czujesz sie wytrzymalszy.
Czujesz sie mniej wytrzymaly.

Czujesz sie silniejszy.

Czujesz sie lepiej.

Czujesz sie mniej zmeczony.
Czujesz sie bardziej zmeczony.

Czujesz sie znacznie lepiej.

Czujesz sie mniej odporny na trucizne.
Czujesz sie bardziej odporny na trucizne.

Czujesz sie mniej zmeczony mentalnie.

Czujesz sie bardziej glodny.

```

**Comment by Dranjam** [comment]
Czujesz sie silniejszy.
Czujesz sie oslabiony.
Czujesz sie zreczniejszy.
Czujesz sie bardziej niezdarny.
Czujesz sie bardziej wytrzymaly. 
Czujesz sie mniej wytrzymaly. 
Czujesz sie bardziej inteligentny. 
Czujesz sie mniej inteligentny. 
Czujesz sie bardziej odwazny.  
Czujesz sie mniej odwazny. 
Czujesz sie mniej zmeczony mentalnie. 
Czujesz sie bardziej zmeczony mentalnie. 
Czujesz sie bardziej glodny.
Czujesz sie mniej glodny. 
Czujesz sie lepiej.  
Czujesz sie gorzej. 
Czujesz sie mniej zmeczony.  
Czujesz sie bardziej zmeczony.  
Czujesz sie bardziej niespokojny.
Czujesz sie mniej niespokojny. 
Czujesz sie znacznie lepiej.

Czujesz sie bardziej odporny na .*?\.
Czujesz sie mniej odporny na .*?\.

Uzupełnienie do powyższego.

**Comment by thaerro** [comment]
`Otaczajacy cie smrod rozwiewa sie.`

**Comment by asikowe** [comment]
Odnosisz wrazenie, ze bedziesz teraz sobie lepiej radzic w zauwazaniu tego, co ukryte.
Odnosisz wrazenie, ze bedziesz teraz sobie gorzej radzic w zauwazaniu tego, co ukryte.
