### ISSUE TITLE
Trolle jaskiniowe

### ISSUE THREAD

**Issue by joszinsan** [tjurczyk/arkadia#814]
![jaskiniowe](https://user-images.githubusercontent.com/75902147/101987994-53e24c80-3c97-11eb-8b07-b980a32937d6.jpg)

Trolle jaskiniowe nie mieszczą się w swoim polu po komendzie /zabici2 przez co nieładnie się rozjeżdża.

**Comment by Delwing** [comment]
tam masz jakieś wpisy typu plytowa i grzbiecie - nie potrzeba jakiś wyjątków może na to?

**Comment by joszinsan** [comment]
Płytowa jest z Zamku Drachenfels, więc na razie chyba zbędna. Grzbiecie jest z karawany, pełna nazwa to "XXX YYY wielblad ze skrzynia na grzbiecie".
