### ISSUE TITLE
blokada triggerow przy czytaniu listow / tablic itp

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#830]
Zablokowanie części triggerów przy takich sytuacjach:

"....
Jesli zda wam sie na co, wezcie kiedy wam wygodnie.

Do zobaczenia!(skrypty): Ok, staty zresetowane
(skrypty): Licznik zresetowany
G."

**Comment by Delwing** [comment]
W związku z tym, że czytanie wiadomości na tablicy ma typ "other", nie ma tego jak sensownie zrobić.
