### ISSUE TITLE
Niewykonywanie komend pre- i post- przy zbieraniu monet/kamieni

### ISSUE THREAD

**Issue by asikowe** [tjurczyk/arkadia#846]
Czy byłaby możliwość dodania do skryptów kondycji, że jeśli pojawi się komunikat "Weź co?", to nie są wykonywane dalsze komendy pre- i post- pojemników?

Przykład:

**Zbieranie monet:**
Wez co?
Otwierasz spory szafirowy plecak.
Wloz co do czego?
Zamykasz spory szafirowy plecak.

**Zbieranie kamieni:**
Wez co?
Umm, co chcesz ocenic?
Otwierasz oliwkowa wytarta sakiewke.
Wloz co do czego?
Zamykasz oliwkowa wytarta sakiewke.

**Comment by Delwing** [comment]
Niestety nie jest to możliwe, komendy są wysyłane na raz, zanim przyjdzie zwrotka z Arkadii.
