### ISSUE TITLE
Ogluchy

### ISSUE THREAD

**Issue by Aruccio** [tjurczyk/arkadia#864]
A jakby tak zrobić też to oznaczenie w states_window na ogłuszenie od herbowej i hełmu? I granitowego, nie jestem pewna, czy oznacza :)

**Comment by DarkTriss** [comment]
Na pewno nie pokazuje sie w states_window ogluszenie od kamiennego golema:
 
Niespodziewanie kamienny golem wyciaga reke i uderza w glowe X.
