### ISSUE TITLE
nierozpoznane ziolo: cztery delikatne czerwone grzyby

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#866]
Cztery delikatne czerwone grzyby odmieniaja sie nastepujaco:

  Mianownik: cztery delikatne czerwone grzyby,
 Dopelniacz: czterech delikatnych czerwonych grzybow,
   Celownik: czterem delikatnym czerwonym grzybom,
    Biernik: cztery delikatne czerwone grzyby,
  Narzednik: czterema delikatnymi czerwonymi grzybami,
Miejscownik: czterech delikatnych czerwonych grzybach.

Rozpoznawane nazwy: grzyb, ziolo i muchomor czerwony.

Ladny okaz Muchomora czerwonego (Amanita muscaria). Ma plaski, czerwony kapelusz z bialymi plamkami i biala, dosc dluga
noge. Wyglada ladnie, jednak jest trujacy.

Oceniasz, ze cztery delikatne czerwone grzyby waza 280 gramow, zas ich objetosc wynosi 36 mililitrow.
Sa tu 4 sztuki nie majace razem zadnej wartosci.

**Comment by Delwing** [comment]
Poprawione.
