### ISSUE TITLE
nowy stoper

### ISSUE THREAD

**Issue by Roslinek** [tjurczyk/arkadia#911]
Podejscie pod mury silnie bronionego garnizonu nie jest najlepszym pomyslem...

**Comment by Delwing** [comment]
@Roslinek `W tej chwili myjesz podloge. Jesli chcesz zaczac robic cos innego, to po prostu przestan.` a to nie jest tak, że tu będzie jakiś opis na start i na koniec?

**Comment by Roslinek** [comment]
umyj podloge
Przyklekasz i zaczynasz powoli i dokladnie szorowac szmata podloge, starajac sie pozbyc wszystkich zabrudzen.

W tej chwili myjesz podloge. Jesli chcesz zaczac robic cos innego, to po prostu przestan.

Konczysz myc podloge i podnosisz sie z kleczek, prostujac zmeczone plecy.
