### ISSUE TITLE
Dodanie blockerów i pausers

### ISSUE THREAD

**Issue by Polish323** [tjurczyk/arkadia#922]
Hej, z gry na Arce zauważyłem następujące frazy, które należy dodać do blockerów i pausers w mapperze.

Blockers:
- Probujesz isc naprzod, ale sliski lod sprawia, ze wywracasz sie na nim.

Pausers:
- Zanurzasz sie pod wode.
- Wynurzasz sie z wody lapczywie lapiac powietrze w pluca.

**Comment by thaerro** [comment]
Jeszcze takie znalazłem, które blokują followa w mapie.

Pausers:

```
Zaczynasz przeszukiwac piasek.
Po chwili cala ta czynnosc zaczyna byc nudna. W piasku chyba nie ma niczego poza zgnilymi
wodorostami i bezwartosciowymi kawalkami drewna.
```

```
Zaczynasz przeszukiwac piasek.
Po chwili wysilku udaje ci sie wymacac cos palcami. Ostroznie wygrzebujesz maly przedmiot,
oczyszczajac go przy okazji z piachu i alg.
```
