### ISSUE TITLE
Własne URL/ścieżki do plików

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia#924]
Możliwość w configu/imie.json dodania własnych URL lub ścieżki do lokalnego pliku dla "ściagalnych" baz typu zioła/magiki/klucze.
Parser by sprawdzał czy config jest ustawiony, jeśli nie, brałby ustawienie defaultowe.

**Comment by Delwing** [comment]
Zakładałbym, że jeżeli odczuwa ktoś potrzebę podmiany plików to dlatego, że są jakieś nieścisłości.
Tak  jak my dzielimy się skryptami to może warto by było poprawić te pliki?

**Comment by Monolith18** [comment]
> Zakładałbym, że jeżeli odczuwa ktoś potrzebę podmiany plików to dlatego, że są jakieś nieścisłości.
> Tak jak my dzielimy się skryptami to może warto by było poprawić te pliki?

Niekoniecznie. W plikach magiki/klucze są stringi, które skrypty podświetlają. Czasami jest potrzeba podświetlenia konkretnych itemów nie-magików i nie znaczy to, że w pliku są jakieś nieścisłości.
Jeśli chodzi o zioła, to ja się tym nie zajmuje.
Uważam po prostu, że fajnie jest mieć możliwość konfiguracji tych parametrów i używania innych plików niż defaultowe.

**Comment by Delwing** [comment]
Oczywiście, ale te pliki są stworzone w konkretnych celach, np. podświetlenie przedmiotów można realizować na inne sposoby. Żeby to ustawienia powstało wiąże się z tym dodatkowa praca - jeżeli ktoś to zrobi i wystawi PR to przejrzę z chęcią, natomiast ja nie planuję tutaj wprowadzać żadnych zmian.
