### ISSUE TITLE
Wyjrzyj przez okno / ob widok - Bindowane dynamicznie w dylizansie lub na statku

### ISSUE THREAD

**Issue by Monolith18** [tjurczyk/arkadia#925]
Fajnie by było gdyby można było zrobić dynamicznego binda pod dajmy na to CTRL-1 lub ] kiedy się jest w dyliżansie lub na statku.

**Comment by Delwing** [comment]
Nie bardzo mam teraz czas podbiec, jakaś komenda jest w wozach?

**Comment by Monolith18** [comment]
Z tego co pamiętam w dyliżansie jest "wyjrzyj przez okno" a na jednostkach pływających jest "obejrzyj widok"

**Comment by Delwing** [comment]
Pytam dokładnie o wóz, bo dla dyliżansów i statków znam komendę :)

**Comment by Monolith18** [comment]
Aha
Nie zrozumiałem, że chodzi dokładnie o wóz a środek transportu.
To nie wiem jaka komenda jest w wozie :) chyba spójrz:)
