### ISSUE TITLE
Zioła Działania uzupełnienie

### ISSUE THREAD

**Issue by thaerro** [tjurczyk/arkadia#951]
Cześć,
Czy można zmienić działanie szałwii?
`zaostrzony podluzny lisc (szalwia)`

Jest przypisane stare działanie tego zioła:
   ` xx | szalwia                 | przyloz: +kon +zmc ` 
Które już tak nie działa.

Obecnie mam takie działanie dotyczące szałwii

```
zjedz ziolo
Zjadasz zaostrzony podluzny lisc (szalwia).
Czujesz sie mniej zmeczony mentalnie.
```

**Comment by Delwing** [comment]
Poprawione.
