### ISSUE TITLE
[Zioła] - Działanie zioła nostrzyk

### ISSUE THREAD

**Issue by thaerro** [tjurczyk/arkadia#975]
Cześć,
Poproszę o rozwinięcie możliwego działania zioła nostrzyk. Póki co mamy:
   ` 22 | nostrzyk                | przezuj: -zmc || rozgryz: -kon +glod `

A jest jeszcze **odtruwające** działanie podczas przeżucia.

```
Przezuwasz smukla zielona lodyge (nostrzyk).
Czujesz sie znacznie lepiej.
Czujesz sie mniej zmeczony.
```

**Comment by Delwing** [comment]
Dodane, dzięki.
