### ISSUE TITLE
Medalion wiedzminski

### ISSUE THREAD

**Issue by mwarzec** [tjurczyk/arkadia#983]
Wiedzminski medalion w ksztalcie glowy kota odmienia sie nastepujaco:

  Mianownik: wiedzminski medalion w ksztalcie glowy kota,
 Dopelniacz: wiedzminskiego medalionu w ksztalcie glowy kota,
   Celownik: wiedzminskiemu medalionowi w ksztalcie glowy kota,
    Biernik: wiedzminski medalion w ksztalcie glowy kota,
  Narzednik: wiedzminskim medalionem w ksztalcie glowy kota,
Miejscownik: wiedzminskim medalionie w ksztalcie glowy kota.

Rozpoznawane nazwy: medalion, naszyjnik, bizuteria, amulet, naszyjnik w ksztalcie glowy kota, bizuteria w
ksztalcie glowy kota i amulet w ksztalcie glowy kota.

======= Oceniasz starannie wiedzminski medalion w ksztalcie glowy kota. ========

Na srebrzystym lancuszku o dosc grubych, mocnych oczkach, zawieszono odlany w calosci ze srebra medalion. Wisior
owy wyprofilowany zostal tak, aby przypominal rozwarta w bitewnym ryku glowe kota,ktorego kly szczerza sie wrogo. 
W miejscu oczu potwora wprawiono dwa malutkie jak ziarnka piachu rubiny - ich czysta, gleboko czerwona 
powierzchnia odbija jednak kazdy promyk swiatla, skrzac sie refleksami i sprawiajac, ze bestia wydaje sie groznie 
lypac slepiami. Amulet wyglada zupelnie jak te, ktore noszone sa przez wedrujacych po swiecie mutantow, zabojcow 
potworow - wiedzminow.

Oceniasz, ze wiedzminski medalion w ksztalcie glowy kota wazy 380 gramow, zas jego objetosc wynosi 280 mililitrow.
Wydaje ci sie, ze jest wart okolo 6300 miedziakow, czyli 26 zl, 5 sr.
Wyglada na to, ze moglby ci jeszcze naprawde dlugo (8d) sluzyc.
Zostal wykonany ze srebra.
Sadzac po delikatnym drzeniu w medalionie zostala zakleta jakas magia.

**Comment by Delwing** [comment]
Już dodany.
